"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  Activity, AlertTriangle, BarChart3, CheckCircle2, ChevronRight, CircleGauge, Clock3,
  ExternalLink, Eye, FileCheck2, FileText, Filter, Globe2, ImageIcon, LayoutDashboard,
  Copy, Info as InfoIcon, Lightbulb, Link2, MousePointerClick, RefreshCw, Route, Save, Search, Settings2, Tags, TrendingDown, UsersRound,
} from "lucide-react";
import { EmptyState, IconPill, MetricCard, PageHeader, SectionHeader, StatusBadge, Surface } from "@/components/ui/norwyn-design-system";
import type { LandingDashboardContext, LandingDashboardTab, LandingInsightCriterion, LandingInsightMaturity, LandingMetric } from "@/modules/landing-pages/types";

const tabs: Array<{ key: LandingDashboardTab; label: string; adminOnly?: boolean }> = [
  { key: "overview", label: "Visão Geral" }, { key: "insights", label: "Insights" }, { key: "journey", label: "Jornada" }, { key: "criteria", label: "Critérios" }, { key: "performance", label: "Desempenho" },
  { key: "behavior", label: "Comportamento", adminOnly: true }, { key: "attribution", label: "Atribuição", adminOnly: true },
  { key: "content", label: "Conteúdo" }, { key: "health", label: "Saúde" },
  { key: "events", label: "Eventos", adminOnly: true }, { key: "versions", label: "Versões", adminOnly: true },
  { key: "qa", label: "QA e Integridade", adminOnly: true },
];
const statusLabels: Record<string, string> = { active: "Ativa", tracking: "Rastreada", DRAFT: "Rascunho", DEV: "DEV", QA: "Em QA", HML: "HML", AWAITING_APPROVAL: "Aguardando aprovação", APPROVED: "Aprovada", REJECTED: "Reprovada", READY_FOR_PROD: "Pronta para PROD", PROD: "Produção" };

function valueOf(metric: LandingMetric, percent = false) {
  if (metric.value === null) return "Não disponível";
  return percent ? `${metric.value.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%` : metric.value.toLocaleString("pt-BR");
}
function comparisonOf(metric: LandingMetric, percent = false) {
  if (metric.previous === null || metric.value === null) return undefined;
  if (percent) return `${(metric.value - metric.previous).toLocaleString("pt-BR", { maximumFractionDigits: 1 })} p.p. vs. período anterior`;
  if (metric.previous === 0) return metric.value === 0 ? "Estável" : "Sem base anterior";
  const delta = ((metric.value - metric.previous) / metric.previous) * 100;
  return `${delta >= 0 ? "+" : ""}${delta.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% vs. período anterior`;
}
function formatPercent(value: number | null) {
  return value === null ? "—" : `${value.toLocaleString("pt-BR", { minimumFractionDigits: 1, maximumFractionDigits: 1 })}%`;
}
function formatMoney(value: number | null) { return value === null ? "Não disponível" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value); }
function countLabel(value: number, singular: string, plural: string) {
  return `${value.toLocaleString("pt-BR")} ${value === 1 ? singular : plural}`;
}
function formatDate(value: string | null, withTime = true) {
  if (!value) return "Não disponível";
  return new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", day: "2-digit", month: "2-digit", year: "numeric", ...(withTime ? { hour: "2-digit", minute: "2-digit" } : {}) }).format(new Date(value));
}
function tabFrom(value: string | null, isAdmin: boolean): LandingDashboardTab {
  const allowed = tabs.filter((tab) => isAdmin || !tab.adminOnly).map((tab) => tab.key);
  return allowed.includes(value as LandingDashboardTab) ? value as LandingDashboardTab : "overview";
}

export function LandingPagesAdminPage({ context }: { context: LandingDashboardContext }) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const isAdmin = context.roleMode === "ADMIN";
  const activeTab = tabFrom(searchParams.get("tab"), isAdmin);
  const journeyDimension = searchParams.get("journey_by") ?? "origin";
  const [query, setQuery] = useState(searchParams.get("q") ?? "");
  const [product, setProduct] = useState(searchParams.get("product") ?? "all");
  const [campaign, setCampaign] = useState(searchParams.get("campaign") ?? "all");
  const [environment, setEnvironment] = useState(searchParams.get("environment") ?? "all");
  const [status, setStatus] = useState(searchParams.get("status") ?? "all");
  const [domain, setDomain] = useState(searchParams.get("domain") ?? "all");
  const [customStart, setCustomStart] = useState(searchParams.get("start") ?? "");
  const [customEnd, setCustomEnd] = useState(searchParams.get("end") ?? "");
  const visibleLandings = useMemo(() => context.landings.filter((item) => {
    const text = `${item.name} ${item.productName} ${item.campaign} ${item.domain}`.toLocaleLowerCase("pt-BR");
    return (!query.trim() || text.includes(query.trim().toLocaleLowerCase("pt-BR"))) && (product === "all" || item.productName === product) && (campaign === "all" || item.campaign === campaign) && (environment === "all" || item.environment === environment) && (status === "all" || item.status === status) && (domain === "all" || item.domain === domain);
  }), [campaign, context.landings, domain, environment, product, query, status]);

  function navigate(updates: Record<string, string | null>) {
    const params = new URLSearchParams(searchParams.toString());
    for (const [key, value] of Object.entries(updates)) value ? params.set(key, value) : params.delete(key);
    router.replace(`/landing-pages?${params.toString()}`, { scroll: false });
  }
  function applyFilters() {
    navigate({ q: query || null, product: product === "all" ? null : product, campaign: campaign === "all" ? null : campaign, environment: environment === "all" ? null : environment, status: status === "all" ? null : status, domain: domain === "all" ? null : domain });
  }
  if (context.diagnostic || !context.selected) return <main className="min-h-screen bg-[color:var(--ds-bg)] p-4 sm:p-6"><EmptyState title="Landing Pages indisponível">{context.diagnostic ?? "Aguardando dados."}</EmptyState></main>;

  const selected = context.selected;
  return <main className="min-h-screen bg-[color:var(--ds-bg)] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <PageHeader eyebrow="Marketing" title="Landing Pages" description="Acompanhe desempenho, conteúdo, atribuição e saúde das páginas em um único lugar." aside={<div className="flex flex-wrap gap-2"><StatusBadge tone={isAdmin ? "primary" : "info"}>{isAdmin ? "ADMIN" : "ESPECIALISTA"}</StatusBadge><StatusBadge tone="success">{context.landings.length} LP{context.landings.length === 1 ? "" : "s"}</StatusBadge></div>} />
    <Surface className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1.5fr_repeat(5,minmax(0,1fr))_auto]">
      <label className="relative block"><Search className="absolute left-3 top-3.5 h-4 w-4 text-[color:var(--ds-text-muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === "Enter" && applyFilters()} placeholder="Buscar LP por nome..." className="h-11 w-full rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] pl-10 pr-3 text-sm text-[color:var(--ds-text)] outline-none focus:border-[color:var(--ds-primary)]" /></label>
      <FilterSelect label="Produto" value={product} values={context.filters.products} onChange={setProduct} /><FilterSelect label="Campanha" value={campaign} values={context.filters.campaigns} onChange={setCampaign} /><FilterSelect label="Ambiente" value={environment} values={context.filters.environments} onChange={setEnvironment} /><FilterSelect label="Status" value={status} values={context.filters.statuses} onChange={setStatus} /><FilterSelect label="Domínio" value={domain} values={context.filters.domains} onChange={setDomain} />
      <button type="button" onClick={applyFilters} className="inline-flex h-11 items-center justify-center gap-2 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-primary)] px-4 text-sm font-semibold text-white"><Filter className="h-4 w-4" />Filtrar</button>
    </div><div className="flex flex-wrap items-center gap-2 border-t border-[color:var(--ds-border)] pt-4">{(["today", "7d", "30d"] as const).map((key) => <button key={key} type="button" onClick={() => navigate({ period: key, start: null, end: null })} className={`rounded-full border px-4 py-2 text-sm font-semibold ${context.period.key === key ? "border-[color:var(--ds-primary)] bg-[color:var(--ds-primary)] text-white" : "border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] text-[color:var(--ds-text-secondary)]"}`}>{key === "today" ? "Hoje" : key === "7d" ? "7 dias" : "30 dias"}</button>)}<input aria-label="Início do período personalizado" type="date" value={customStart} onChange={(event) => setCustomStart(event.target.value)} className="h-10 rounded-full border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] px-3 text-sm text-[color:var(--ds-text-secondary)]" /><input aria-label="Fim do período personalizado" type="date" value={customEnd} onChange={(event) => setCustomEnd(event.target.value)} className="h-10 rounded-full border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] px-3 text-sm text-[color:var(--ds-text-secondary)]" /><button type="button" disabled={!customStart || !customEnd} onClick={() => navigate({ period: "custom", start: customStart, end: customEnd })} className="h-10 rounded-full border border-[color:var(--ds-border-strong)] px-4 text-sm font-semibold text-[color:var(--ds-text)] disabled:opacity-40">Aplicar período</button>{isAdmin ? <label className="inline-flex h-10 items-center gap-2 rounded-full border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] px-3 text-sm font-semibold text-[color:var(--ds-text-secondary)]"><input type="checkbox" checked={context.traffic.includesTest} onChange={(event) => navigate({ include_test: event.target.checked ? "1" : null })} />Incluir tráfego de teste</label> : null}<span className="ml-auto inline-flex items-center gap-2 text-sm text-[color:var(--ds-text-muted)]"><Clock3 className="h-4 w-4" />{context.period.label}{context.traffic.excludedEvents > 0 ? ` · ${context.traffic.excludedEvents} eventos técnicos fora das métricas` : ""}</span></div></Surface>
    <div className="grid gap-5 xl:grid-cols-[290px_minmax(0,1fr)]"><Surface className="h-fit p-3 sm:p-3"><div className="mb-3 flex items-center justify-between px-2"><p className="text-sm font-semibold text-[color:var(--ds-text)]">Páginas</p><span className="text-xs text-[color:var(--ds-text-muted)]">{visibleLandings.length}</span></div><div className="grid max-h-[580px] gap-2 overflow-y-auto">{visibleLandings.map((item) => <button type="button" key={item.landingKey} onClick={() => navigate({ lp: item.landingKey, tab: "overview" })} className={`w-full rounded-[var(--ds-radius-md)] border p-3 text-left transition ${selected.landingKey === item.landingKey ? "border-[color:var(--ds-primary)] bg-[color:var(--ds-primary-soft)]" : "border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] hover:border-[color:var(--ds-border-strong)]"}`}><div className="flex items-start justify-between gap-2"><p className="font-semibold leading-5 text-[color:var(--ds-text)]">{item.name}</p><ChevronRight className="mt-0.5 h-4 w-4 shrink-0 text-[color:var(--ds-text-muted)]" /></div><p className="mt-1 text-xs text-[color:var(--ds-text-secondary)]">{item.productName}</p><div className="mt-3 flex flex-wrap gap-1.5"><StatusBadge tone={item.status === "active" ? "success" : "neutral"}>{statusLabels[item.status] ?? item.status}</StatusBadge><StatusBadge tone="info">{item.environment}</StatusBadge></div></button>)}{!visibleLandings.length ? <EmptyState title="Nenhuma LP encontrada">Ajuste os filtros para ampliar a busca.</EmptyState> : null}</div></Surface>
      <div className="min-w-0 space-y-5"><Surface><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 gap-3"><IconPill icon={LayoutDashboard} tone="primary" /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold text-[color:var(--ds-text)]">{selected.name}</h2><StatusBadge tone="success">{statusLabels[selected.status] ?? selected.status}</StatusBadge></div><p className="mt-1 text-sm text-[color:var(--ds-text-secondary)]">{selected.productName} · {selected.campaign}</p><p className="mt-2 break-all text-sm text-[color:var(--ds-text-muted)]">{selected.domain} · {selected.version ?? "Versão não disponível"}</p></div></div>{context.content.previewUrl ? <a href={context.content.previewUrl} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center justify-center gap-2 rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border-strong)] bg-[color:var(--ds-surface-solid)] px-4 text-sm font-semibold text-[color:var(--ds-text)]"><Eye className="h-4 w-4" />Abrir preview<ExternalLink className="h-3.5 w-3.5" /></a> : null}</div></Surface>
        <nav className="flex gap-2 overflow-x-auto rounded-[var(--ds-radius-lg)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface)] p-2 shadow-[var(--ds-shadow-sm)]" aria-label="Visões da landing page">{tabs.filter((tab) => isAdmin || !tab.adminOnly).map((tab) => <button key={tab.key} type="button" onClick={() => navigate({ tab: tab.key })} className={`shrink-0 rounded-full px-4 py-2.5 text-sm font-semibold ${activeTab === tab.key ? "bg-[color:var(--ds-primary)] text-white" : "text-[color:var(--ds-text-secondary)] hover:bg-[color:var(--ds-bg-soft)]"}`}>{tab.label}</button>)}</nav>
        {activeTab === "overview" ? <Overview context={context} /> : null}{activeTab === "insights" ? <Insights context={context} /> : null}{activeTab === "journey" ? <Journey context={context} dimension={journeyDimension} onDimensionChange={(value) => navigate({ journey_by: value })} /> : null}{activeTab === "criteria" ? <Criteria context={context} /> : null}{activeTab === "performance" ? <Performance context={context} /> : null}{activeTab === "behavior" ? <Behavior context={context} /> : null}{activeTab === "attribution" ? <Attribution context={context} /> : null}{activeTab === "content" ? <Content context={context} /> : null}{activeTab === "health" ? <Health context={context} simplified={!isAdmin} /> : null}{activeTab === "events" ? <Events context={context} /> : null}{activeTab === "versions" ? <Versions context={context} /> : null}{activeTab === "qa" ? <QaIntegrity context={context} /> : null}
      </div></div>
  </div></main>;
}

function FilterSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-11 min-w-0 rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] px-3 text-sm text-[color:var(--ds-text)]"><option value="all">{label}: todos</option>{values.map((item) => <option key={item} value={item}>{item}</option>)}</select>; }
function Metrics({ context }: { context: LandingDashboardContext }) { const period = context.period.label; return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6"><MetricCard label="Visitantes únicos" value={valueOf(context.metrics.visitors)} period={period} comparison={comparisonOf(context.metrics.visitors)} tone="primary" icon={UsersRound} /><MetricCard label="Sessões" value={valueOf(context.metrics.sessions)} period={period} comparison={comparisonOf(context.metrics.sessions)} tone="info" icon={Activity} /><MetricCard label="Page views" value={valueOf(context.metrics.pageViews)} period={period} comparison={comparisonOf(context.metrics.pageViews)} icon={Eye} /><MetricCard label="Oferta visualizada" value={valueOf(context.metrics.offerViews)} period={period} comparison={comparisonOf(context.metrics.offerViews)} tone="warning" icon={Tags} /><MetricCard label="Cliques no checkout" value={valueOf(context.metrics.checkoutClicks)} period={period} comparison={comparisonOf(context.metrics.checkoutClicks)} tone="success" icon={MousePointerClick} /><MetricCard label="LP → checkout" value={valueOf(context.metrics.conversionRate, true)} period="Sessões únicas" comparison={comparisonOf(context.metrics.conversionRate, true)} tone="success" icon={BarChart3} /></div>; }
function Overview({ context }: { context: LandingDashboardContext }) { return <div className="space-y-5"><Metrics context={context} /><SalesExecutive context={context} /><div className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><Trend context={context} /><Funnel context={context} /></div><div className="grid gap-5 lg:grid-cols-2"><Sections context={context} /><TopEvents context={context} /></div><Attribution context={context} /></div>; }
function SalesExecutive({ context }: { context: LandingDashboardContext }) {
  const quality = context.attributionQuality;
  return <div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><Surface><SectionHeader eyebrow="Vendas confirmadas" title="De onde vieram as vendas?" description="Somente Hotmart confirmada com vínculo determinístico por source_sck e chave Norwyn. Proximidade de data ou nome não atribui venda." />{context.confirmedSalesBySource.length ? <div className="mt-5 divide-y divide-[color:var(--ds-border)]">{context.confirmedSalesBySource.map((item) => <div key={item.source} className="grid gap-3 py-4 sm:grid-cols-[1fr_repeat(3,auto)] sm:items-center sm:gap-7"><div><p className="font-semibold text-[color:var(--ds-text)]">{item.source}</p><p className="mt-1 text-xs text-[color:var(--ds-text-muted)]">Confiança {item.confidence.toLocaleLowerCase("pt-BR")}</p></div><Info label="Vendas" value={item.sales.toLocaleString("pt-BR")} /><Info label="Receita" value={formatMoney(item.revenue)} /><Info label="Sessão → venda" value={formatPercent(item.sessionToSaleRate)} /></div>)}</div> : <div className="mt-5"><EmptyState title="Nenhuma origem determinística no período">As vendas confirmadas continuam contabilizadas, mas não são distribuídas entre canais sem evidência.</EmptyState></div>}</Surface><Surface><SectionHeader eyebrow="Qualidade da atribuição" title="Cobertura do período" description="A cobertura mede vendas confirmadas cuja origem pôde ser determinada." /><p className="mt-5 text-4xl font-semibold text-[color:var(--ds-text)]">{formatPercent(quality.originCoverage)}</p><p className="mt-2 text-sm text-[color:var(--ds-text-secondary)]">{quality.originDetermined} de {quality.confirmed} vendas com origem determinada</p><div className="mt-5 grid grid-cols-2 gap-3"><Info label="Campanha" value={quality.campaignDetermined.toLocaleString("pt-BR")} /><Info label="Anúncio" value={quality.adDetermined.toLocaleString("pt-BR")} /><Info label="Links Norwyn" value={context.journey.purchases.trackedByNorwyn.toLocaleString("pt-BR")} /><Info label="Sem origem" value={quality.unknown.toLocaleString("pt-BR")} /></div><div className="mt-5 border-t border-[color:var(--ds-border)] pt-4"><p className="text-sm font-semibold text-[color:var(--ds-text)]">Saúde da jornada: {context.journeyHealth.status}</p><p className="mt-1 text-xs leading-5 text-[color:var(--ds-text-muted)]">Operacional {context.journeyHealth.operational.toLowerCase()} · mensuração {context.journeyHealth.measurement.toLowerCase()}. Performance comercial não define este status.</p></div></Surface></div>;
}
function Performance({ context }: { context: LandingDashboardContext }) { return <div className="space-y-5"><Metrics context={context} /><div className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><Trend context={context} /><Funnel context={context} /></div><Sections context={context} /></div>; }
function Insights({ context }: { context: LandingDashboardContext }) {
  return <div className="space-y-5">
    <Surface><SectionHeader eyebrow="Leitura operacional" title="O que os dados estão indicando" description="Cada leitura separa o fato observado, a regra acionada, uma hipótese e o próximo passo. Hipóteses não são conclusões." /><div className="mt-5 flex items-start gap-3 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-info-soft)] p-4"><InfoIcon className="mt-0.5 h-5 w-5 shrink-0 text-[color:var(--ds-info)]" /><p className="text-sm leading-6 text-[color:var(--ds-text-secondary)]">Maturidade indica o volume do dado. Confiança só aparece quando o nível Insight é atingido e considera amostra e repetição no período anterior. Nenhuma das duas é decidida por IA, e a Norwyn não transforma correlação em causalidade.</p></div></Surface>
    {context.insights.length ? <div className="grid gap-5 xl:grid-cols-2">{context.insights.map((item) => <Surface key={`${item.id}-${item.maturity ?? "initial"}`} className="space-y-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><IconPill icon={item.id === "minimum_sample" ? AlertTriangle : Lightbulb} tone={item.confidence === "Alta" ? "success" : item.maturity === "Insight" ? "warning" : "neutral"} /><div><p className="text-xs font-semibold uppercase text-[color:var(--ds-text-muted)]">O que aconteceu</p><h3 className="mt-1 text-xl font-semibold text-[color:var(--ds-text)]">{item.title}</h3><p className="mt-1 text-xs text-[color:var(--ds-text-muted)]">{item.analyzedSessions.toLocaleString("pt-BR")} sessões analisadas</p></div></div><div className="flex flex-wrap justify-end gap-2">{item.maturity ? <StatusBadge tone={item.maturity === "Insight" ? "success" : item.maturity === "Em observação" ? "warning" : "neutral"}>{item.maturity}</StatusBadge> : <StatusBadge tone="neutral">Aguardando prévia</StatusBadge>}{item.confidence ? <StatusBadge tone={item.confidence === "Alta" ? "success" : item.confidence === "Média" ? "warning" : "neutral"}>Confiança {item.confidence.toLowerCase()}</StatusBadge> : null}</div></div><p className="text-base leading-7 text-[color:var(--ds-text)]">{item.whatHappened}</p><div className="grid gap-4 sm:grid-cols-2"><InsightPart label="Por que chamou atenção" value={item.whyAttention} /><InsightPart label="O que pode significar" value={item.hypothesis} /><InsightPart label="Evidência" value={item.evidence.join(" · ")} /><InsightPart label={`O que fazer agora · ${item.allowedAction}`} value={item.nextStep} /></div></Surface>)}</div> : <Surface><EmptyState title="Nenhum critério acionado">Os dados do período não acionaram uma leitura configurada. Isso não significa ausência de oportunidade; apenas que nenhuma regra objetiva foi satisfeita.</EmptyState></Surface>}
  </div>;
}
function InsightPart({ label, value }: { label: string; value: string }) { return <div className="border-l-2 border-[color:var(--ds-border-strong)] pl-3"><p className="text-xs font-semibold uppercase text-[color:var(--ds-text-muted)]">{label}</p><p className="mt-1 text-sm leading-6 text-[color:var(--ds-text-secondary)]">{value}</p></div>; }
function Journey({ context, dimension, onDimensionChange }: { context: LandingDashboardContext; dimension: string; onDimensionChange: (value: string) => void }) {
  const dimensions = [{ key: "origin", label: "Origem", enabled: context.journey.availableDimensions.origin }, { key: "campaign", label: "Campanha", enabled: context.journey.availableDimensions.campaign }, { key: "landing", label: "Landing key", enabled: context.journey.availableDimensions.landingKey }, { key: "version", label: "Versão", enabled: context.journey.availableDimensions.version }, { key: "device", label: "Dispositivo", enabled: context.journey.availableDimensions.device }];
  return <div className="space-y-5">
    <Surface><SectionHeader eyebrow="Jornada" title="Como as pessoas avançaram pela página" description="Contagem por sessões únicas. Uma queda mostra uma mudança observada, não prova um problema ou sua causa." /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Maior perda absoluta" value={context.journey.highlights.biggestAbsoluteLoss ?? "Não disponível"} /><Info label="Maior perda percentual" value={context.journey.highlights.biggestPercentageLoss ?? "Não disponível"} /><Info label="Melhor avanço" value={context.journey.highlights.bestProgress ?? "Não disponível"} /><Info label="Menor avanço" value={context.journey.highlights.lowestProgress ?? "Não disponível"} /></div></Surface>
    <JourneyFlow title="Jornada principal confiável" description="Sessão e checkout contam sessões únicas da mesma coorte. Compra mostra as vendas confirmadas do produto no período; a atribuição indica quais têm vínculo comprovado com a LP." steps={context.journey.detailed} />
    <JourneyExecutive context={context} />
    <Surface><SectionHeader eyebrow="Comportamento" title="Sinais auxiliares" description="Profundidade, oferta e CTAs ajudam a entender o uso, mas a instrumentação atual não prova uma sequência obrigatória entre eles." /><div className="mt-5 grid gap-4 sm:grid-cols-2">{context.journey.behavioral.map((item) => <div key={item.key} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><p className="font-semibold text-[color:var(--ds-text)]">{item.label}</p><div className="mt-3 flex gap-6"><Info label="Sessões únicas" value={item.sessions.toLocaleString("pt-BR")} /><Info label="Disparos" value={item.events.toLocaleString("pt-BR")} /></div><p className="mt-3 text-sm leading-6 text-[color:var(--ds-text-secondary)]">{item.note}</p></div>)}</div></Surface>
    {context.journey.purchaseLimitation ? <Notice text={context.journey.purchaseLimitation} tone="warning" /> : null}
    <Surface><SectionHeader eyebrow="Quebras" title="Jornada por contexto" description="Compare taxas sem rotular automaticamente uma origem como melhor ou pior." /><PurchaseAttributionSummary context={context} /><div className="mt-5 flex flex-wrap gap-2">{dimensions.map((item) => <button type="button" key={item.key} disabled={!item.enabled} title={!item.enabled ? "Este dado ainda não é enviado pelo tracking atual." : undefined} onClick={() => onDimensionChange(item.key)} className={`rounded-full border px-4 py-2 text-sm font-semibold ${dimension === item.key ? "border-[color:var(--ds-primary)] bg-[color:var(--ds-primary)] text-white" : "border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] text-[color:var(--ds-text-secondary)]"} disabled:cursor-not-allowed disabled:opacity-40`}>{item.label}</button>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-[color:var(--ds-text-muted)]"><tr><th className="pb-3 font-medium">Contexto</th><th className="pb-3 text-right font-medium">Sessões</th><th className="pb-3 text-right font-medium">Oferta</th><th className="pb-3 text-right font-medium">Checkout</th><th className="pb-3 text-right font-medium">Taxa checkout</th><th className="pb-3 text-right font-medium">Hotmart confirmada + origem</th></tr></thead><tbody className="divide-y divide-[color:var(--ds-border)]">{context.journey.breakdowns.map((item) => <tr key={item.label}><td className="py-3 font-semibold text-[color:var(--ds-text)]">{item.label}</td><td className="py-3 text-right">{item.sessions.toLocaleString("pt-BR")}</td><td className="py-3 text-right">{item.offerViews.toLocaleString("pt-BR")}</td><td className="py-3 text-right">{item.checkoutClicks.toLocaleString("pt-BR")}</td><td className="py-3 text-right">{item.checkoutRate === null ? "—" : `${item.checkoutRate.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%`}</td><td className="py-3 text-right">{item.purchases === null ? "Não disponível" : item.purchases.toLocaleString("pt-BR")}</td></tr>)}</tbody></table>{!context.journey.breakdowns.length ? <EmptyState title="Aguardando dados">Não há base confiável para esta quebra no período.</EmptyState> : null}</div></Surface>
  </div>;
}
function JourneyFlow({ title, description, steps }: { title: string; description: string; steps: LandingDashboardContext["journey"]["detailed"] }) { return <Surface><SectionHeader eyebrow="Funil" title={title} description={description} /><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{steps.map((step, index) => <div key={step.key} className="relative rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><div className="flex items-center justify-between gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[color:var(--ds-primary-soft)] text-sm font-semibold text-[color:var(--ds-primary)]">{index + 1}</span>{index > 0 ? <Route className="h-4 w-4 text-[color:var(--ds-text-muted)]" /> : null}</div><p className="mt-4 text-sm font-semibold text-[color:var(--ds-text-secondary)]">{step.label}</p><p className="mt-1 text-3xl font-semibold text-[color:var(--ds-text)]">{step.value === null ? "—" : step.value.toLocaleString("pt-BR")}</p>{index > 0 ? <div className="mt-3 space-y-1 text-xs text-[color:var(--ds-text-muted)]"><p>{step.fromPreviousPercent === null ? "Avanço não disponível" : `${step.fromPreviousPercent.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% da etapa anterior`}</p><p>{step.fromSessionsPercent === null ? "Participação não disponível" : `${step.fromSessionsPercent.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% das sessões`}</p><p>{step.lossFromPrevious === null ? "Perda não disponível" : `Perda: ${step.lossFromPrevious.toLocaleString("pt-BR")}`}</p></div> : <p className="mt-3 text-xs text-[color:var(--ds-text-muted)]">Base da jornada</p>}{step.note ? <p className="mt-3 text-xs leading-5 text-[color:var(--ds-warning)]">{step.note}</p> : null}</div>)}</div></Surface>; }
function JourneyExecutive({ context }: { context: LandingDashboardContext }) {
  const { executiveRates, purchases } = context.journey;
  const sessions = context.journey.detailed.find((item) => item.key === "sessions")?.value ?? 0;
  const checkouts = context.journey.detailed.find((item) => item.key === "checkout")?.value ?? 0;
  const cards = [
    { label: "Taxa de checkout", value: executiveRates.checkoutRate, detail: `${checkouts.toLocaleString("pt-BR")} de ${sessions.toLocaleString("pt-BR")} sessões chegaram ao checkout.` },
    { label: "Checkout → compra", value: executiveRates.checkoutToPurchaseRate, detail: `${purchases.confirmed.toLocaleString("pt-BR")} de ${checkouts.toLocaleString("pt-BR")} intenções viraram compra confirmada.` },
    { label: "Conversão da LP", value: executiveRates.landingConversionRate, detail: `${purchases.confirmed.toLocaleString("pt-BR")} compras confirmadas em ${sessions.toLocaleString("pt-BR")} sessões.` },
    { label: "Cobertura de atribuição", value: executiveRates.attributionCoverage, detail: `${purchases.attributed.toLocaleString("pt-BR")} de ${purchases.confirmed.toLocaleString("pt-BR")} compras têm origem determinística.` },
  ];
  return <Surface><SectionHeader eyebrow="Leitura executiva" title="Taxas da jornada" description="Conversão total compara dados do mesmo período; somente a cobertura de atribuição comprova o vínculo da compra com a LP. Uma compra sem atribuição nunca é somada a Direto ou a outro canal." /><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <div key={card.label} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><p className="text-sm font-semibold text-[color:var(--ds-text-secondary)]">{card.label}</p><p className="mt-2 text-3xl font-semibold text-[color:var(--ds-text)]">{formatPercent(card.value)}</p><p className="mt-3 text-xs leading-5 text-[color:var(--ds-text-muted)]">{card.detail}</p></div>)}</div></Surface>;
}
function PurchaseAttributionSummary({ context }: { context: LandingDashboardContext }) {
  const purchases = context.journey.purchases;
  return <div className="mt-5 grid gap-3 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-bg-soft)] p-4 sm:grid-cols-2 xl:grid-cols-4"><Info label="Hotmart confirmada + origem" value={countLabel(purchases.originDetermined, "compra", "compras")} /><Info label="Hotmart confirmada + campanha" value={countLabel(purchases.campaignDetermined, "compra", "compras")} /><Info label="Hotmart sem origem" value={countLabel(purchases.unattributed, "compra", "compras")} /><Info label="Meta Purchase" value={purchases.metaReported === null ? "Não comparável nesta LP" : purchases.metaReported.toLocaleString("pt-BR")} /><p className="sm:col-span-2 xl:col-span-4 text-xs leading-5 text-[color:var(--ds-text-muted)]">Os níveis de Hotmart podem se sobrepor: origem determinada também pode ter campanha conhecida. Meta Purchase é um sinal reportado pela plataforma e nunca substitui a venda Hotmart confirmada.</p></div>;
}
function Criteria({ context }: { context: LandingDashboardContext }) { return <div className="space-y-5"><Surface><SectionHeader eyebrow="Governança" title="Critérios explicáveis" description="ADMIN e ESPECIALISTA podem ajustar as regras. Cada alteração fica registrada no histórico da Landing Page." /><div className="mt-5 flex items-start gap-3 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-bg-soft)] p-4"><Settings2 className="mt-0.5 h-5 w-5 shrink-0 text-[color:var(--ds-primary)]" /><p className="text-sm leading-6 text-[color:var(--ds-text-secondary)]">Maturidade mede volume: Prévia permite acompanhar, Em observação permite investigar e comparar, e Insight permite formular hipótese e sugerir teste. Confiança só é calculada no último nível.</p></div></Surface><MaturityEditor maturity={context.insightMaturity} landingKey={context.selected?.landingKey ?? ""} /><div className="grid gap-5 xl:grid-cols-2">{context.criteria.map((criterion) => <CriterionEditor key={criterion.key} criterion={criterion} landingKey={context.selected?.landingKey ?? ""} />)}</div></div>; }
function MaturityEditor({ maturity, landingKey }: { maturity: LandingInsightMaturity; landingKey: string }) {
  const router = useRouter(); const [draft, setDraft] = useState(maturity); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function save() { if (saving) return; setSaving(true); setMessage(null); try { const response = await fetch("/api/landing-pages/criteria", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ landingKey, configType: "maturity", ...draft }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? "Não foi possível salvar a maturidade."); setDraft(payload.maturity); setMessage("Maturidade salva e registrada no histórico."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar a maturidade."); } finally { setSaving(false); } }
  return <Surface><SectionHeader eyebrow="Maturidade do dado" title="Quando uma leitura evolui" description="Os níveis são objetivos e editáveis; a Norwyn não usa IA para escolhê-los." /><div className="mt-5 grid gap-4 md:grid-cols-3"><MaturityLevel title="Prévia" description="Mostra como o comportamento começa a se formar. Pode acompanhar ou verificar; não recomenda alteração." value={draft.previewMinSessions} onChange={(value) => setDraft({ ...draft, previewMinSessions: value })} /><MaturityLevel title="Em observação" description="O comportamento começa a se repetir. Pode investigar e comparar; ainda evita recomendação forte." value={draft.observationMinSessions} onChange={(value) => setDraft({ ...draft, observationMinSessions: value })} /><MaturityLevel title="Insight" description="A amostra oficial foi atingida. Pode formular hipótese, calcular confiança e sugerir próximo teste." value={draft.insightMinSessions} onChange={(value) => setDraft({ ...draft, insightMinSessions: value })} /></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[color:var(--ds-border)] pt-4"><p className="text-xs text-[color:var(--ds-text-muted)]">{draft.updatedAt ? `Alterado por ${draft.updatedBy ?? "usuário Norwyn"} em ${formatDate(draft.updatedAt)}` : "Padrão inicial: 20 / 50 / 100 sessões."}</p><button type="button" disabled={saving} onClick={save} className="inline-flex h-10 items-center gap-2 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-primary)] px-4 text-sm font-semibold text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Salvando..." : "Salvar maturidade"}</button></div>{message ? <p className={`mt-3 text-sm ${message.startsWith("Maturidade salva") ? "text-emerald-700" : "text-red-700"}`}>{message}</p> : null}</Surface>;
}
function MaturityLevel({ title, description, value, onChange }: { title: string; description: string; value: number; onChange: (value: number) => void }) { return <div className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><StatusBadge tone={title === "Insight" ? "success" : title === "Em observação" ? "warning" : "neutral"}>{title}</StatusBadge><p className="mt-3 text-sm leading-6 text-[color:var(--ds-text-secondary)]">{description}</p><div className="mt-4"><NumberField label="A partir de (sessões)" value={value} onChange={onChange} /></div></div>; }
function CriterionEditor({ criterion, landingKey }: { criterion: LandingInsightCriterion; landingKey: string }) {
  const router = useRouter();
  const [draft, setDraft] = useState(criterion);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  async function save() {
    if (saving) return;
    setSaving(true); setMessage(null);
    try {
      const response = await fetch("/api/landing-pages/criteria", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ landingKey, criterionKey: draft.key, thresholdPercent: draft.thresholdPercent, windowDays: draft.windowDays, minSessions: draft.minSessions, mediumSample: draft.mediumSample, highSample: draft.highSample, active: draft.active }) });
      const payload = await response.json().catch(() => null);
      if (!response.ok) throw new Error(payload?.error ?? "Não foi possível salvar o critério.");
      setDraft(payload.criterion); setMessage("Critério salvo e registrado no histórico."); router.refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar o critério."); }
    finally { setSaving(false); }
  }
  return <Surface><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-[color:var(--ds-text)]">{draft.name}</h3><p className="mt-2 text-sm leading-6 text-[color:var(--ds-text-secondary)]">{draft.explanation}</p></div><label className="inline-flex items-center gap-2 text-sm font-semibold text-[color:var(--ds-text)]"><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} />Ativo</label></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Fórmula" value={draft.formula} /><Info label="Por que existe" value={draft.whyItExists} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{draft.key !== "minimum_sample" ? <NumberField label="Limiar (%)" value={draft.thresholdPercent} onChange={(value) => setDraft({ ...draft, thresholdPercent: value })} /> : null}<NumberField label="Janela (dias)" value={draft.windowDays} onChange={(value) => setDraft({ ...draft, windowDays: value })} /><NumberField label="Sessões mínimas" value={draft.minSessions} onChange={(value) => setDraft({ ...draft, minSessions: value })} /><NumberField label="Amostra média" value={draft.mediumSample} onChange={(value) => setDraft({ ...draft, mediumSample: value })} /><NumberField label="Amostra alta" value={draft.highSample} onChange={(value) => setDraft({ ...draft, highSample: value })} /></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[color:var(--ds-border)] pt-4"><p className="text-xs text-[color:var(--ds-text-muted)]">{draft.updatedAt ? `Alterado por ${draft.updatedBy ?? "usuário Norwyn"} em ${formatDate(draft.updatedAt)}` : "Usando configuração inicial sugerida; ainda sem alteração manual."}</p><button type="button" disabled={saving} onClick={save} className="inline-flex h-10 items-center gap-2 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-primary)] px-4 text-sm font-semibold text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Salvando..." : "Salvar critério"}</button></div>{message ? <p className={`mt-3 text-sm ${message.startsWith("Critério salvo") ? "text-emerald-700" : "text-red-700"}`}>{message}</p> : null}</Surface>;
}
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-sm font-semibold text-[color:var(--ds-text-secondary)]">{label}<input type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 h-11 w-full rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] px-3 text-base text-[color:var(--ds-text)] outline-none focus:border-[color:var(--ds-primary)]" /></label>; }
function Trend({ context }: { context: LandingDashboardContext }) { const max = Math.max(1, ...context.daily.map((item) => item.pageViews)); return <Surface><SectionHeader eyebrow="Evolução" title="Movimento no período" description="Page views diários da LP selecionada." />{context.daily.length ? <div className="mt-6 flex h-52 items-end gap-2 border-b border-[color:var(--ds-border)] px-1">{context.daily.map((item) => <div key={item.date} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div title={`${item.date}: ${item.pageViews} page views`} className="w-full max-w-10 rounded-t bg-[color:var(--ds-primary)] transition group-hover:bg-[color:var(--ds-accent)]" style={{ height: `${Math.max(8, (item.pageViews / max) * 160)}px` }} /><span className="hidden text-[10px] text-[color:var(--ds-text-muted)] sm:block">{item.date.slice(5)}</span></div>)}</div> : <EmptyState title="Aguardando dados">A evolução aparece quando houver eventos no período.</EmptyState>}</Surface>; }
function Funnel({ context }: { context: LandingDashboardContext }) { const max = Math.max(1, context.funnel[0]?.value ?? 1); return <Surface><SectionHeader eyebrow="Funil" title="LP até checkout" description="Conversão calculada por sessões únicas." /><div className="mt-5 space-y-4">{context.funnel.map((item) => <div key={item.label}><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span className="font-semibold text-[color:var(--ds-text)]">{item.label}</span><span className="text-[color:var(--ds-text-secondary)]">{item.value.toLocaleString("pt-BR")} {item.rate === null ? "" : `· ${item.rate.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%`}</span></div><div className="h-3 overflow-hidden rounded-full bg-[color:var(--ds-bg-soft)]"><div className="h-full rounded-full bg-[color:var(--ds-accent)]" style={{ width: `${Math.max(item.value ? 8 : 0, (item.value / max) * 100)}%` }} /></div></div>)}</div></Surface>; }
function Sections({ context }: { context: LandingDashboardContext }) { return <Surface><SectionHeader eyebrow="Conteúdo" title="Performance por seção" description="Sessões que visualizaram cada parte rastreada." /><div className="mt-5 divide-y divide-[color:var(--ds-border)]">{context.sections.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-semibold text-[color:var(--ds-text)]">{item.label}</p><p className="text-xs text-[color:var(--ds-text-muted)]">{item.id}</p></div><div className="text-right"><p className="text-lg font-semibold text-[color:var(--ds-text)]">{item.views}</p><p className="text-xs text-[color:var(--ds-text-muted)]">{item.share === null ? "Não disponível" : `${item.share.toLocaleString("pt-BR", { maximumFractionDigits: 0 })}% das sessões`}</p></div></div>)}{!context.sections.length ? <EmptyState title="Aguardando dados">Esta LP ainda não envia eventos de seção.</EmptyState> : null}</div></Surface>; }
function TopEvents({ context }: { context: LandingDashboardContext }) { return <Surface><SectionHeader eyebrow="Eventos" title="Principais eventos" description="Eventos reais recebidos no período." /><div className="mt-5 grid gap-2">{context.topEvents.map((item, index) => <div key={item.name} className="flex items-center gap-3 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-bg-soft)] p-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[color:var(--ds-primary-soft)] text-sm font-semibold text-[color:var(--ds-primary)]">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-semibold text-[color:var(--ds-text)]">{eventLabel(item.name)}</p><p className="text-xs text-[color:var(--ds-text-muted)]">{item.sessions} sessões</p></div><span className="text-lg font-semibold text-[color:var(--ds-text)]">{item.total}</span></div>)}{!context.topEvents.length ? <EmptyState title="Aguardando dados" /> : null}</div></Surface>; }
function Behavior({ context }: { context: LandingDashboardContext }) { return <div className="grid gap-5 lg:grid-cols-2"><Sections context={context} /><TopEvents context={context} /></div>; }
function Attribution({ context }: { context: LandingDashboardContext }) {
  const maturity = context.acquisition.maturity;
  const maturityTone = maturity === "Insight" ? "success" : maturity === "Em observação" ? "warning" : "neutral";
  return <Surface>
    <SectionHeader eyebrow="Aquisição" title="Origem e campanha" description="Como as sessões públicas do período avançaram até o checkout, sem transformar volume inicial em ranking de canais." />
    {context.attribution.length ? <>
      <div className="mt-5 hidden overflow-x-auto md:block">
        <table className="w-full min-w-[720px] text-left text-sm">
          <thead className="text-[color:var(--ds-text-muted)]"><tr><th className="pb-3 font-medium">Origem</th><th className="pb-3 text-right font-medium">Sessões</th><th className="pb-3 text-right font-medium">% das sessões</th><th className="pb-3 text-right font-medium">Checkout</th><th className="pb-3 text-right font-medium">Taxa de checkout</th><th className="pb-3 text-right font-medium">% dos checkouts</th><th className="pb-3 text-right font-medium">Vendas confirmadas</th><th className="pb-3 text-right font-medium">Receita</th></tr></thead>
          <tbody className="divide-y divide-[color:var(--ds-border)]">{context.attribution.map((item) => <tr key={`${item.source}-${item.campaign}`}>
            <td className="py-4 pr-4"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-[color:var(--ds-text)]">{item.source}</span>{item.maturity ? <StatusBadge tone={item.maturity === "Insight" ? "success" : item.maturity === "Em observação" ? "warning" : "neutral"}>{item.maturity}</StatusBadge> : null}</div><span className="mt-1 block text-xs text-[color:var(--ds-text-muted)]">Campanha: {item.campaign}</span></td>
            <td className="py-4 text-right font-semibold text-[color:var(--ds-text)]">{item.sessions.toLocaleString("pt-BR")}</td><td className="py-4 text-right text-[color:var(--ds-text)]">{formatPercent(item.sessionShare)}</td><td className="py-4 text-right font-semibold text-[color:var(--ds-text)]">{item.checkoutClicks.toLocaleString("pt-BR")}</td><td className="py-4 text-right text-[color:var(--ds-text)]">{formatPercent(item.checkoutRate)}</td><td className="py-4 text-right text-[color:var(--ds-text)]">{formatPercent(item.checkoutShare)}</td><td className="py-4 text-right font-semibold text-[color:var(--ds-text)]">{item.purchases === null ? "—" : item.purchases.toLocaleString("pt-BR")}</td><td className="py-4 text-right text-[color:var(--ds-text)]">{item.revenue === null ? "—" : formatMoney(item.revenue)}</td>
          </tr>)}</tbody>
        </table>
      </div>
      <div className="mt-5 grid gap-3 md:hidden">{context.attribution.map((item) => <article key={`${item.source}-${item.campaign}`} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4">
        <div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-[color:var(--ds-text)]">{item.source}</h3><p className="mt-1 text-xs text-[color:var(--ds-text-muted)]">Campanha: {item.campaign}</p></div>{item.maturity ? <StatusBadge tone={item.maturity === "Insight" ? "success" : item.maturity === "Em observação" ? "warning" : "neutral"}>{item.maturity}</StatusBadge> : null}</div>
        <dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><div><dt className="text-[color:var(--ds-text-muted)]">Sessões</dt><dd className="mt-0.5 font-semibold text-[color:var(--ds-text)]">{item.sessions.toLocaleString("pt-BR")} · {formatPercent(item.sessionShare)}</dd></div><div><dt className="text-[color:var(--ds-text-muted)]">Checkout</dt><dd className="mt-0.5 font-semibold text-[color:var(--ds-text)]">{item.checkoutClicks.toLocaleString("pt-BR")} · {formatPercent(item.checkoutShare)}</dd></div><div><dt className="text-[color:var(--ds-text-muted)]">Taxa de checkout</dt><dd className="mt-0.5 font-semibold text-[color:var(--ds-text)]">{formatPercent(item.checkoutRate)}</dd></div><div><dt className="text-[color:var(--ds-text-muted)]">Venda confirmada</dt><dd className="mt-0.5 font-semibold text-[color:var(--ds-text)]">{item.purchases === null ? "—" : `${item.purchases} · ${formatMoney(item.revenue)}`}</dd></div></dl>
      </article>)}</div>
      <div className="mt-5 grid gap-4 border-t border-[color:var(--ds-border)] pt-5 lg:grid-cols-[1fr_0.85fr]">
        <div className="rounded-[var(--ds-radius-md)] bg-[color:var(--ds-bg-soft)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold uppercase text-[color:var(--ds-text-muted)]">Leitura do período</p><h3 className="mt-1 text-lg font-semibold text-[color:var(--ds-text)]">O que os números mostram</h3></div>{maturity ? <StatusBadge tone={maturityTone}>{maturity}</StatusBadge> : <StatusBadge tone="neutral">Aguardando prévia</StatusBadge>}</div><ul className="mt-3 space-y-2 text-sm leading-6 text-[color:var(--ds-text-secondary)]">{context.acquisition.reading.map((line) => <li key={line} className="flex gap-2"><span aria-hidden="true" className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[color:var(--ds-primary)]" />{line}</li>)}</ul></div>
        <div className="space-y-3"><div className="flex gap-3 rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><InfoIcon className="mt-0.5 h-5 w-5 shrink-0 text-[color:var(--ds-info)]" /><div><p className="font-semibold text-[color:var(--ds-text)]">Direto × origem não identificada</p><p className="mt-1 text-sm leading-6 text-[color:var(--ds-text-secondary)]">Direto não possui evidência de origem externa. Origem não identificada possui algum contexto de aquisição, como referência externa, fbclid ou source_sck, mas não pôde ser resolvida. Nenhuma sessão é redistribuída por inferência.</p></div></div><div className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><p className="text-sm font-semibold text-[color:var(--ds-text)]">Vendas por links Norwyn: {countLabel(context.journey.purchases.trackedByNorwyn, "confirmada", "confirmadas")}</p><p className="mt-1 text-sm leading-6 text-[color:var(--ds-text-secondary)]">Há {countLabel(context.journey.purchases.confirmed, "compra Hotmart confirmada", "compras Hotmart confirmadas")} no período; {countLabel(context.attributionQuality.unknown, "continua sem origem determinada", "continuam sem origem determinada")}.</p></div></div>
      </div>
    </> : <div className="mt-5"><EmptyState title="Aguardando dados">Nenhuma atribuição foi recebida no período.</EmptyState></div>}
  </Surface>;
}
function Content({ context }: { context: LandingDashboardContext }) { return <div className="space-y-5"><div className="grid gap-5 lg:grid-cols-[1fr_0.8fr]"><Surface><SectionHeader eyebrow="Página" title={context.content.title} description={context.content.summary} /><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Produto" value={context.selected?.productName ?? "Não disponível"} /><Info label="Campanha" value={context.selected?.campaign ?? "Não disponível"} /><Info label="Versão" value={context.selected?.version ?? "Não disponível"} /><Info label="Ambiente" value={context.selected?.environment ?? "Não disponível"} /></div></Surface><Surface><SectionHeader eyebrow="Oferta" title="Checkout vinculado" description="Identidade comercial encontrada no Catálogo." /><div className="mt-5 space-y-3"><Info label="Hotmart Product ID" value={context.content.hotmartProductId ?? "Não disponível"} /><Info label="Offer ID" value={context.content.hotmartOfferId ?? "Não disponível"} /><Info label="URL" value={context.content.checkoutUrl ?? "Não disponível"} />{context.content.checkoutUrl ? <a href={context.content.checkoutUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-[color:var(--ds-primary)]">Abrir checkout <ExternalLink className="h-4 w-4" /></a> : null}</div></Surface></div><TrackedLinkGenerator baseUrl={context.content.previewUrl} /></div>; }

const trackedLinkPresets = [
  { key: "stories", label: "Instagram · Stories", source: "instagram", medium: "organic", content: "stories" },
  { key: "bio", label: "Instagram · Link da bio", source: "instagram", medium: "organic", content: "bio" },
  { key: "whatsapp", label: "WhatsApp · Grupo", source: "whatsapp", medium: "group", content: "grupo_whatsapp" },
  { key: "site", label: "Site Juliana", source: "site", medium: "owned", content: "site_juliana" },
  { key: "meta", label: "Meta Ads", source: "meta", medium: "paid", content: "ads" },
] as const;

function TrackedLinkGenerator({ baseUrl }: { baseUrl: string | null }) {
  const [presetKey, setPresetKey] = useState<(typeof trackedLinkPresets)[number]["key"]>("stories");
  const [copied, setCopied] = useState(false);
  const preset = trackedLinkPresets.find((item) => item.key === presetKey) ?? trackedLinkPresets[0];
  const generatedUrl = useMemo(() => {
    if (!baseUrl) return null;
    const url = new URL(baseUrl);
    url.searchParams.set("utm_source", preset.source);
    url.searchParams.set("utm_medium", preset.medium);
    url.searchParams.set("utm_campaign", "imersao_zumbido");
    url.searchParams.set("utm_content", preset.content);
    return url.toString();
  }, [baseUrl, preset]);
  return <Surface><SectionHeader eyebrow="Divulgação" title="Gerar link rastreado" description="Use a convenção oficial da campanha Imersão Zumbido." /><div className="mt-5 grid gap-3 lg:grid-cols-[260px_minmax(0,1fr)_auto]"><select aria-label="Origem do link" value={presetKey} onChange={(event) => { setPresetKey(event.target.value as typeof presetKey); setCopied(false); }} className="h-11 rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] px-3 text-sm font-semibold text-[color:var(--ds-text)]">{trackedLinkPresets.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><input aria-label="URL rastreada" readOnly value={generatedUrl ?? "Domínio ainda não disponível"} className="h-11 min-w-0 rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-bg-soft)] px-3 text-sm text-[color:var(--ds-text-secondary)]" /><button type="button" disabled={!generatedUrl} onClick={async () => { if (!generatedUrl) return; await navigator.clipboard.writeText(generatedUrl); setCopied(true); }} className="inline-flex h-11 items-center justify-center gap-2 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-primary)] px-4 text-sm font-semibold text-white disabled:opacity-40"><Copy className="h-4 w-4" />{copied ? "Copiado" : "Copiar"}</button></div></Surface>;
}

function Health({ context, simplified }: { context: LandingDashboardContext; simplified: boolean }) {
  const router = useRouter();
  const [checking, setChecking] = useState(false);
  const [checkMessage, setCheckMessage] = useState<string | null>(null);
  const health = context.health;
  const core = [["Disponibilidade", health.availability, Globe2], ["Checkout", health.checkout, Link2], ["Tracking", health.tracking, Activity], ["Último evento", formatDate(health.recentEventAt), Clock3]] as const;
  const technical = [["HTTP", health.httpStatus === null ? "Não disponível" : String(health.httpStatus), CircleGauge], ["Links", health.links, Link2], ["Imagens", health.images, ImageIcon], ["SEO básico", health.seo, FileText], ["Performance técnica", health.technicalPerformance, BarChart3], ["Integridade publicada", health.publishedIntegrity, FileCheck2], ["Erros recentes", health.errors === null ? "Não disponível" : String(health.errors), AlertTriangle]] as const;
  const overallTone = health.overallStatus === "healthy" ? "success" : health.overallStatus === "critical" ? "danger" : health.overallStatus === "warning" ? "warning" : "neutral";
  async function verifyNow() {
    if (checking) return;
    setChecking(true);
    setCheckMessage(null);
    try {
      const response = await fetch("/api/landing-pages/health", { method: "POST" });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error ?? "Não foi possível concluir a verificação.");
      setCheckMessage("Verificação concluída.");
      router.refresh();
    } catch (error) {
      setCheckMessage(error instanceof Error ? error.message : "Não foi possível concluir a verificação.");
    } finally {
      setChecking(false);
    }
  }
  return <div className="space-y-5">
    <Surface className={health.overallStatus === "critical" ? "border-rose-200" : health.overallStatus === "warning" ? "border-amber-200" : "border-emerald-200"}>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div><p className="text-xs font-semibold uppercase text-[color:var(--ds-text-muted)]">Saúde da página</p><div className="mt-2 flex items-center gap-3"><h3 className="text-3xl font-semibold text-[color:var(--ds-text)]">{health.overallLabel}</h3><StatusBadge tone={overallTone}>{health.overallLabel}</StatusBadge></div><p className="mt-2 max-w-3xl text-sm leading-6 text-[color:var(--ds-text-secondary)]">{health.guidance ?? "Aguardando a primeira verificação completa."}</p><p className="mt-2 text-xs text-[color:var(--ds-text-muted)]">Última verificação: {formatDate(health.components.map((item) => item.lastCheckedAt).filter(Boolean).sort().at(-1) ?? health.lastCheckedAt)}</p></div>
        {!simplified ? <button type="button" disabled={checking} onClick={verifyNow} className="inline-flex h-11 items-center justify-center gap-2 rounded-[var(--ds-radius-md)] bg-[color:var(--ds-primary)] px-4 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${checking ? "animate-spin" : ""}`} />{checking ? "Verificando..." : "Verificar agora"}</button> : null}
      </div>
      {checkMessage ? <p className="mt-3 text-sm font-semibold text-[color:var(--ds-text-secondary)]">{checkMessage}</p> : null}
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{health.components.map((item) => <div key={item.key} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-bg-soft)] p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[color:var(--ds-text)]">{item.label}</p><StatusBadge tone={item.status === "healthy" ? "success" : item.status === "critical" ? "danger" : item.status === "warning" ? "warning" : "neutral"}>{item.status === "healthy" ? "OK" : item.status === "critical" ? "Crítico" : item.status === "warning" ? "Atenção" : "Não verificado"}</StatusBadge></div><p className="mt-2 text-sm leading-5 text-[color:var(--ds-text-secondary)]">{item.message}</p>{!simplified ? <p className="mt-2 text-xs text-[color:var(--ds-text-muted)]">{formatDate(item.lastCheckedAt)}</p> : null}</div>)}</div>
    </Surface>
    {!simplified ? <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{core.map(([label, value, Icon]) => <HealthCard key={label} label={label} value={value} icon={Icon} />)}{technical.map(([label, value, Icon]) => <HealthCard key={label} label={label} value={value} icon={Icon} />)}</div>
      <Surface><SectionHeader eyebrow="Diagnóstico técnico" title="Checks do Presence" description="Detalhes de HTTP, redirect, certificado, atribuição, checkout e tracking." /><div className="mt-5 grid gap-3">{health.diagnostics.map((item) => <details key={item.key} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-[color:var(--ds-text)]">{item.label}</p><p className="mt-1 break-all text-xs text-[color:var(--ds-text-muted)]">{item.url || "Evento de tracking"}</p></div><StatusBadge tone={item.status === "healthy" ? "success" : item.status === "critical" ? "danger" : item.status === "warning" ? "warning" : "neutral"}>{item.status}</StatusBadge></div></summary><div className="mt-4 grid gap-3 border-t border-[color:var(--ds-border)] pt-4 sm:grid-cols-2 lg:grid-cols-3"><Info label="HTTP" value={item.httpStatus === null ? "Não disponível" : String(item.httpStatus)} /><Info label="Duração" value={item.responseTimeMs === null ? "Não disponível" : `${item.responseTimeMs} ms`} /><Info label="HTTPS/certificado" value={item.sslOk === null ? "Não disponível" : item.sslOk ? `Válido${item.sslExpiresAt ? ` até ${formatDate(item.sslExpiresAt, false)}` : ""}` : "Revisar"} /><Info label="Origem esperada" value={item.expectedOrigin ?? "Não se aplica"} /><Info label="Origem observada" value={item.observedOrigin ?? "Não disponível"} /><Info label="Checkout observado" value={item.observedCheckout === null ? "Não disponível" : item.observedCheckout ? "Sim" : "Não"} /></div>{item.redirectChain.length ? <div className="mt-3"><Info label="Cadeia de redirect" value={item.redirectChain.join(" → ")} /></div> : null}{item.error ? <div className="mt-3"><Notice text={item.error} tone="warning" /></div> : null}</details>)}</div></Surface>
      <div className="grid gap-5 lg:grid-cols-2"><Surface><SectionHeader eyebrow="Integridade" title="Divergências detectadas" description="Diferenças registradas sem correção automática." /><div className="mt-5 space-y-2">{health.divergences.map((item, index) => <Notice key={index} text={item} tone="warning" />)}{!health.divergences.length ? <Notice text="Nenhuma divergência registrada para esta LP." tone="success" /> : null}</div></Surface><Surface><SectionHeader eyebrow="Atenção" title="Alertas e QA" description="Ocorrências abertas nas fontes de monitoramento." /><div className="mt-5 space-y-2">{health.alerts.map((item, index) => <Notice key={index} text={item} tone="warning" />)}{!health.alerts.length ? <Notice text="Nenhum alerta aberto nas fontes disponíveis." tone="success" /> : null}</div></Surface></div>
    </> : null}
    <Surface><SectionHeader eyebrow="Monitoramento" title="Cobertura atual" description={`Domínio: ${health.domain}`} /><p className="mt-4 text-sm leading-6 text-[color:var(--ds-text-secondary)]">Os links de campanha são verificados como SIMULATED/test e não entram nas métricas públicas.</p></Surface>
  </div>;
}
function Events({ context }: { context: LandingDashboardContext }) { return <div className="space-y-5"><Surface><SectionHeader eyebrow="Tracking" title="Eventos recentes" description="Últimos eventos de negócio no período selecionado." /><div className="mt-5 divide-y divide-[color:var(--ds-border)]">{context.recentEvents.map((item) => <div key={item.id} className="flex flex-col gap-1 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[color:var(--ds-text)]">{item.label}</p><p className="text-xs text-[color:var(--ds-text-muted)]">{item.section ?? item.source}</p></div><time className="text-sm text-[color:var(--ds-text-secondary)]">{formatDate(item.occurredAt)}</time></div>)}{!context.recentEvents.length ? <EmptyState title="Aguardando dados" /> : null}</div></Surface><Surface><SectionHeader eyebrow="Auditoria técnica" title="Tráfego fora das métricas de negócio" description="Registros preservados para diagnóstico e excluídos por classificação semântica, não por nome textual." /><div className="mt-5 divide-y divide-[color:var(--ds-border)]">{context.traffic.technicalAudit.map((item) => <div key={item.reason} className="grid grid-cols-[1fr_auto_auto] gap-4 py-3 text-sm"><span className="font-semibold text-[color:var(--ds-text)]">{item.reason}</span><span className="text-[color:var(--ds-text-secondary)]">{item.sessions} sessões</span><span className="text-[color:var(--ds-text-secondary)]">{item.events} eventos</span></div>)}{!context.traffic.technicalAudit.length ? <p className="text-sm text-[color:var(--ds-text-muted)]">Nenhum tráfego técnico foi identificado no período.</p> : null}</div></Surface></div>; }
function Versions({ context }: { context: LandingDashboardContext }) { return <Surface><SectionHeader eyebrow="Publicação" title="Versões" description="Histórico da estrutura de versionamento existente." /><div className="mt-5 grid gap-3 md:grid-cols-2">{context.versions.map((item) => <div key={item.id} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[color:var(--ds-text)]">{item.version}</p><StatusBadge tone="info">{statusLabels[item.status] ?? item.status}</StatusBadge></div><p className="mt-3 text-sm leading-6 text-[color:var(--ds-text-secondary)]">{item.summary}</p><p className="mt-3 text-xs text-[color:var(--ds-text-muted)]">{formatDate(item.createdAt)}</p></div>)}{!context.versions.length ? <EmptyState title="Aguardando dados">A LP rastreada ainda não possui versão no Landing System.</EmptyState> : null}</div></Surface>; }
function QaIntegrity({ context }: { context: LandingDashboardContext }) { return <div className="grid gap-5 lg:grid-cols-2"><Surface><SectionHeader eyebrow="Qualidade" title="Execuções de QA" /><div className="mt-5 space-y-3">{context.qa.map((item) => <div key={item.id} className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-[color:var(--ds-text)]">{item.status}</p><span className="text-xs text-[color:var(--ds-text-muted)]">{formatDate(item.completedAt)}</span></div><p className="mt-2 text-sm text-[color:var(--ds-text-secondary)]">{item.passed} aprovados · {item.warnings} atenções · {item.blockers} bloqueios</p></div>)}{!context.qa.length ? <EmptyState title="Aguardando QA" /> : null}</div></Surface><Surface><SectionHeader eyebrow="Governança" title="Aprovações" /><div className="mt-5 space-y-3">{context.approvals.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] p-4"><div><p className="font-semibold text-[color:var(--ds-text)]">{item.type}</p><p className="text-xs text-[color:var(--ds-text-muted)]">Solicitada em {formatDate(item.requestedAt)}</p></div><StatusBadge tone={item.decision === "APPROVED" ? "success" : item.decision === "REJECTED" ? "danger" : "warning"}>{item.decision}</StatusBadge></div>)}{!context.approvals.length ? <EmptyState title="Aguardando aprovação" /> : null}</div></Surface></div>; }
function HealthCard({ label, value, icon }: { label: string; value: string; icon: typeof Globe2 }) { const waiting = /não disponível|aguardando/i.test(value); return <div className="rounded-[var(--ds-radius-md)] border border-[color:var(--ds-border)] bg-[color:var(--ds-surface-solid)] p-4 shadow-[var(--ds-shadow-sm)]"><div className="flex items-center gap-3"><IconPill icon={icon} tone={waiting ? "neutral" : "success"} /><div className="min-w-0"><p className="text-sm text-[color:var(--ds-text-secondary)]">{label}</p><p className="mt-1 break-words font-semibold text-[color:var(--ds-text)]">{value}</p></div></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-[var(--ds-radius-md)] bg-[color:var(--ds-bg-soft)] p-4"><p className="text-xs font-medium text-[color:var(--ds-text-muted)]">{label}</p><p className="mt-1 break-words text-sm font-semibold text-[color:var(--ds-text)]">{value}</p></div>; }
function Notice({ text, tone }: { text: string; tone: "warning" | "success" }) { const Icon = tone === "success" ? CheckCircle2 : AlertTriangle; return <div className={`flex gap-3 rounded-[var(--ds-radius-md)] border p-3 ${tone === "success" ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><Icon className={`mt-0.5 h-4 w-4 shrink-0 ${tone === "success" ? "text-emerald-700" : "text-amber-700"}`} /><p className="text-sm leading-5 text-[color:var(--ds-text)]">{text}</p></div>; }
function eventLabel(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
