-- Auto-generated by scripts/generate_financeiro_seed.py

-- Source: D:\Jass_\Download_HD\TESTE Fluxo de caixa V2.xlsx



begin;



create or replace function app_private.fin_auto_provisao_imposto()
returns trigger
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_centro text;
  v_categoria_id uuid;
  v_subcategoria_id uuid;
  v_percentual numeric(7,4);
  v_valor numeric(14,2);
begin
  if new.tipo <> 'entrada'
     or new.status <> 'realizado'
     or new.origem in ('provisao_imposto', 'importacao') then
    return new;
  end if;

  select nome into v_centro
  from public.fin_centros_resultado
  where id = new.centro_resultado_id;

  if v_centro <> 'Infoproduto' then
    return new;
  end if;

  v_percentual := coalesce(
    nullif((select valor->>'percentual_provisao_imposto'
            from public.fin_config
            where tenant_id = new.tenant_id and chave = 'financeiro'), '')::numeric,
    0.06
  );
  v_valor := round(new.valor * v_percentual, 2);

  select c.id, s.id
    into v_categoria_id, v_subcategoria_id
  from public.fin_categorias c
  left join public.fin_subcategorias s
    on s.categoria_id = c.id
   and s.nome = 'Impostos sobre vendas'
  where c.tenant_id = new.tenant_id
    and c.nome = 'Deduções da Receita'
    and c.tipo = 'saida'
  limit 1;

  if v_categoria_id is null or v_subcategoria_id is null or v_valor <= 0 then
    return new;
  end if;

  if not exists (
    select 1
    from public.fin_lancamentos
    where tenant_id = new.tenant_id
      and origem = 'provisao_imposto'
      and lancamento_origem_id = new.id
  ) then
    insert into public.fin_lancamentos (
      tenant_id, data_pagamento, mes_competencia, tipo, status,
      centro_resultado_id, categoria_id, subcategoria_id, forma_pagamento,
      banco_id, descricao, valor, observacao, origem, lancamento_origem_id, created_by
    )
    values (
      new.tenant_id,
      app_private.fin_due_date(date_trunc('month', new.data_pagamento)::date + interval '1 month', 20),
      new.mes_competencia,
      'saida',
      'previsto',
      new.centro_resultado_id,
      v_categoria_id,
      v_subcategoria_id,
      'boleto',
      new.banco_id,
      'Provisão automática de imposto - ' || new.descricao,
      v_valor,
      'Gerado automaticamente a partir do lançamento ' || new.id,
      'provisao_imposto',
      new.id,
      new.created_by
    );
  end if;

  return new;
end;
$$;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
vals(nome, ativo) as (values
    ('Infoproduto', true),
    ('Clínica', true),
    ('Palestras', true),
    ('Administrativo fixo', true),
    ('Não operacional', true)
)
insert into public.fin_centros_resultado (tenant_id, nome, ativo)
select t.tenant_id, v.nome, v.ativo from tenant_scope t cross join vals v
on conflict (tenant_id, nome) do update set ativo = excluded.ativo;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
vals(nome) as (values
    ('Fixo'),
    ('Variável'),
    ('Operacional'),
    ('Não operacional')
)
insert into public.fin_naturezas (tenant_id, nome, ativo)
select t.tenant_id, v.nome, true from tenant_scope t cross join vals v
on conflict (tenant_id, nome) do update set ativo = excluded.ativo;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1)
insert into public.fin_bancos (tenant_id, nome, apelido, saldo_inicial, ativo)
select tenant_id, 'Histórico (a reclassificar)', 'Histórico', 0, true from tenant_scope
on conflict (tenant_id, nome) do update
set apelido = excluded.apelido, ativo = true;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
bank_scope as (
  select b.id as banco_id, b.tenant_id
  from public.fin_bancos b
  join tenant_scope t on t.tenant_id = b.tenant_id
  where b.nome = 'Histórico (a reclassificar)'
)
insert into public.fin_cartoes (tenant_id, nome, banco_id, dia_fechamento, dia_vencimento, limite, ativo)
select tenant_id, 'Histórico (a reclassificar)', banco_id, 3, 10, null, true from bank_scope
on conflict (tenant_id, nome) do update
set banco_id = excluded.banco_id, dia_fechamento = 3, dia_vencimento = 10, ativo = true;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
vals(tipo, nome, natureza, dre_grupo) as (values
    ('entrada'::public.fin_tipo_lancamento, 'Entradas', 'Operacional', 'receita_bruta'),
    ('entrada'::public.fin_tipo_lancamento, 'Movimentações Financeiras', 'Não operacional', 'resultado_financeiro'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Administrativas', 'Fixo', 'despesas_administrativas'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Clínica', 'Variável', 'despesas_operacionais'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Operacionais', 'Operacional', 'despesas_operacionais'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Pessoal', 'Fixo', 'despesas_pessoal'),
    ('saida'::public.fin_tipo_lancamento, 'Movimentações Financeiras', 'Não operacional', 'resultado_financeiro'),
    ('saida'::public.fin_tipo_lancamento, 'Deduções da Receita', 'Variável', 'deducoes'),
    ('saida'::public.fin_tipo_lancamento, 'Custos Diretos', 'Variável', 'custos_diretos'),
    ('saida'::public.fin_tipo_lancamento, 'Taxas de Plataforma', 'Variável', 'taxas_plataforma'),
    ('saida'::public.fin_tipo_lancamento, 'Agência de Marketing', 'Variável', 'coproducao'),
    ('saida'::public.fin_tipo_lancamento, 'Comissões de Afiliados', 'Variável', 'comissoes_afiliados'),
    ('saida'::public.fin_tipo_lancamento, 'Outros Custos Diretos', 'Variável', 'outros_custos_diretos'),
    ('saida'::public.fin_tipo_lancamento, 'Depreciação', 'Não operacional', 'depreciacao'),
    ('saida'::public.fin_tipo_lancamento, 'IRPJ/CSLL', 'Variável', 'irpj_csll')
)
insert into public.fin_categorias (tenant_id, natureza_id, tipo, nome, dre_grupo, ativo)
select t.tenant_id, n.id, v.tipo, v.nome, v.dre_grupo, true
from tenant_scope t
join vals v on true
join public.fin_naturezas n on n.tenant_id = t.tenant_id and n.nome = v.natureza
on conflict (tenant_id, tipo, nome) do update
set natureza_id = excluded.natureza_id, dre_grupo = excluded.dre_grupo, ativo = true;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
vals(tipo, categoria, nome, dre_grupo) as (values
    ('entrada'::public.fin_tipo_lancamento, 'Entradas', 'Clínica', 'receita_bruta'),
    ('entrada'::public.fin_tipo_lancamento, 'Entradas', 'Entradas', 'receita_bruta'),
    ('entrada'::public.fin_tipo_lancamento, 'Movimentações Financeiras', 'Movimentações Financeiras', 'resultado_financeiro'),
    ('saida'::public.fin_tipo_lancamento, 'Movimentações Financeiras', 'Movimentações Financeiras', 'resultado_financeiro'),
    ('saida'::public.fin_tipo_lancamento, 'Movimentações Financeiras', 'Distribuição dos Lucros', 'nao_dre'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Administrativas', 'Contabilidade', 'despesas_administrativas'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Administrativas', 'Contas fixas', 'despesas_administrativas'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Administrativas', 'Equipamentos e materiais', 'despesas_administrativas'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Clínica', 'Clínica', 'despesas_operacionais'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Operacionais', 'Equipamentos e materiais', 'despesas_operacionais'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Operacionais', 'Imposto', 'deducoes'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Operacionais', 'Pedagógico', 'despesas_operacionais'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Operacionais', 'Softwares e ferramentas', 'despesas_operacionais'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Pessoal', 'INSS', 'despesas_pessoal'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Pessoal', 'Prestação de serviços', 'despesas_pessoal'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Pessoal', 'Pro-labore', 'despesas_pessoal'),
    ('saida'::public.fin_tipo_lancamento, 'Despesas Pessoal', 'Contabilidade', 'despesas_pessoal'),
    ('saida'::public.fin_tipo_lancamento, 'Deduções da Receita', 'Impostos sobre vendas', 'deducoes'),
    ('saida'::public.fin_tipo_lancamento, 'Taxas de Plataforma', 'Greenn', 'taxas_plataforma'),
    ('saida'::public.fin_tipo_lancamento, 'Taxas de Plataforma', 'Hotmart', 'taxas_plataforma'),
    ('saida'::public.fin_tipo_lancamento, 'Taxas de Plataforma', 'TMB', 'taxas_plataforma'),
    ('saida'::public.fin_tipo_lancamento, 'Agência de Marketing', 'Coprodução', 'coproducao'),
    ('saida'::public.fin_tipo_lancamento, 'Depreciação', 'Depreciação', 'depreciacao')
)
insert into public.fin_subcategorias (tenant_id, categoria_id, nome, dre_grupo, ativo)
select t.tenant_id, c.id, v.nome, v.dre_grupo, true
from tenant_scope t
join vals v on true
join public.fin_categorias c on c.tenant_id = t.tenant_id and c.tipo = v.tipo and c.nome = v.categoria
on conflict (tenant_id, categoria_id, nome) do update
set dre_grupo = excluded.dre_grupo, ativo = true;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
vals(nome) as (values
    ('Formação AASI Premium'),
    ('Combo Fono Premium'),
    ('Imersão Zumbido'),
    ('Imersão CROS e BiCROS - Indicação, Adaptação, Verificação e Validação'),
    ('Mapa do Raciocínio Clínico'),
    ('Protocolo Fono Premium 2026'),
    ('Pack de modelo zumbido: anamnese, avaliação, orientação e atividades'),
    ('Fundamentos da Timpanometria'),
    ('O que considerar antes de precificar sua consulta de zumbido'),
    ('Manual da acufenometria completa'),
    ('Passo a passo mascaramento plat'),
    ('Histórico (a reclassificar)')
)
insert into public.fin_cursos (tenant_id, nome, ativo)
select t.tenant_id, v.nome, true from tenant_scope t cross join vals v
on conflict (tenant_id, nome) do update set ativo = true;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1)
insert into public.fin_config (tenant_id, chave, valor)
select tenant_id, 'financeiro', '{"limite_capex":5000,"tratamento_coproducao":"despesa","percentual_provisao_imposto":0.06}'::jsonb
from tenant_scope
on conflict (tenant_id, chave) do update
set valor = public.fin_config.valor || excluded.valor;

with tenant_scope as (select id as tenant_id from public.tenants where lower(nome) like '%juliana coutinho%' order by created_at limit 1),
infoproduto as (
  select id as centro_id, tenant_id
  from public.fin_centros_resultado
  where nome = 'Infoproduto'
),
members as (
  select tm.tenant_id, tm.user_id, tm.role::text as role
  from public.tenant_members tm
  join tenant_scope t on t.tenant_id = tm.tenant_id
)
insert into public.fin_perfis_usuario (tenant_id, user_id, perfil, centros_permitidos, ativo)
select
  m.tenant_id,
  m.user_id,
  case when m.role = 'MARKETING_PARTNER' then 'marketing'::public.fin_perfil_acesso else 'admin'::public.fin_perfil_acesso end,
  case when m.role = 'MARKETING_PARTNER' then array[i.centro_id]::uuid[] else array[]::uuid[] end,
  true
from members m
left join infoproduto i on i.tenant_id = m.tenant_id
where m.role in ('ADMIN', 'MARKETING_PARTNER')
on conflict (tenant_id, user_id) do update
set perfil = excluded.perfil,
    centros_permitidos = excluded.centros_permitidos,
    ativo = true;

create unique index if not exists fin_lancamentos_import_hash_idx
on public.fin_lancamentos (tenant_id, ((metadata->>'import_hash')))
where origem = 'importacao' and metadata ? 'import_hash';

commit;
