-- Auto-generated by scripts/generate_financeiro_seed.py
-- Source rows: 2..26

begin;

create temporary table if not exists fin_import_raw (
  source_row integer,
  data_pagamento date,
  mes_competencia date,
  centro text,
  tipo public.fin_tipo_lancamento,
  natureza text,
  categoria text,
  subcategoria text,
  descricao text,
  forma_pagamento public.fin_forma_pagamento,
  valor numeric(14,2),
  raw_pagamento text,
  raw_mes_competencia text,
  import_hash text
) on commit drop;

truncate table fin_import_raw;

insert into fin_import_raw (
  source_row, data_pagamento, mes_competencia, centro, tipo, natureza,
  categoria, subcategoria, descricao, forma_pagamento, valor,
  raw_pagamento, raw_mes_competencia, import_hash
)
values
    (2, '2026-01-05'::date, '2026-01-01'::date, 'Não operacional', 'saida'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'CDB BANCO INTER', 'conta_bancaria'::public.fin_forma_pagamento, 10000.00::numeric, 'Conta bancária', '', '29cca247fc4de0e76d8b01d6d1f77e986d37a368'),
    (3, '2026-01-05'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 10500.00::numeric, 'Conta bancária', '', '0a2ee4a3f82cd44e3c687fe7b09f18f80e6e9d96'),
    (4, '2026-01-09'::date, '2026-01-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Equipamentos e materiais', 'TELEPROMPTER', 'conta_bancaria'::public.fin_forma_pagamento, 363.79::numeric, 'Conta bancária', '', '00785af1bf56543b20a3e96bbfb324d52545ba13'),
    (5, '2026-01-09'::date, '2026-01-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'CANVA', 'cartao_credito'::public.fin_forma_pagamento, 24.15::numeric, 'Cartão de crédito', '', '7422e6177e81a0d174a682471404c889f4b4c2b9'),
    (6, '2026-01-10'::date, '2026-01-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', 'CERTIFICADO MEC', 'conta_bancaria'::public.fin_forma_pagamento, 2000.00::numeric, 'Conta bancária', 'Janeiro', 'bb4f90f3cece6bbeb952b465fd705b4319915ef6'),
    (7, '2026-01-12'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contabilidade', 'CONTABILIZEI', 'cartao_credito'::public.fin_forma_pagamento, 195.00::numeric, 'Cartão de crédito', '', 'f41d4eed36e1681887631334f6a217f440950c3a'),
    (8, '2026-01-19'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'CONSELHO DE FONO', 'cartao_credito'::public.fin_forma_pagamento, 165.00::numeric, 'Cartão de crédito', '', 'af0647432964524a1e31b472f66274387177b8cc'),
    (9, '2026-01-20'::date, '2026-01-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 100.00::numeric, 'Conta bancária', '', '885692e5d1bc0bb318ddb7a5a76baf9625b13545'),
    (10, '2026-01-20'::date, '2026-01-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 180.00::numeric, 'Conta bancária', '', '41f496c606a2883c9ab5f4473f6b2b428304a8fe'),
    (11, '2026-01-20'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 500.00::numeric, 'Conta bancária', '', '921d0e257d2ebc5886acaad9ae5ecb654100ff5a'),
    (12, '2026-01-22'::date, '2025-12-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'INSS', 'DARF', 'conta_bancaria'::public.fin_forma_pagamento, 168.08::numeric, 'Conta bancária', 'Dezembro', '82b3c795043a9182847d114ef462cc0c40e22e68'),
    (13, '2026-01-22'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Distribuição dos Lucros', 'DISTRIBUIÇÃO DOS LUCROS', 'conta_bancaria'::public.fin_forma_pagamento, 3390.00::numeric, 'Conta bancária', '', '3faf4c07bb1825973daa7fd96d199830abf3d839'),
    (14, '2026-01-22'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'INTERNET', 'conta_bancaria'::public.fin_forma_pagamento, 102.30::numeric, 'Conta bancária', '', 'be9af3bc6769a2e65ab5b565bd06a38e4388c0c9'),
    (15, '2026-01-23'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Distribuição dos Lucros', 'DISTRIBUIÇÃO DOS LUCROS', 'conta_bancaria'::public.fin_forma_pagamento, 10000.00::numeric, 'Conta bancária', '', 'e5fb2f806e6e2e1f8af090ae64abb64c178eeb46'),
    (16, '2026-01-27'::date, '2026-01-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'HOTMART', 'conta_bancaria'::public.fin_forma_pagamento, 4395.20::numeric, 'Conta bancária', '', 'ddadc9d03868bee35dc14ec6a866ad7df5dfce7b'),
    (17, '2026-01-29'::date, '2026-01-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 3695.11::numeric, 'Conta bancária', '', 'afad9cb67524123d3f4f662e43229e00fbcfd557'),
    (18, '2026-02-02'::date, '2026-02-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'CONSELHO DE FONO', 'conta_bancaria'::public.fin_forma_pagamento, 570.29::numeric, 'Conta bancária', '', 'f847e97a0227bf148aaca80b05ec94264ccc5e16'),
    (19, '2026-02-02'::date, '2026-01-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Prestação de serviços', 'SALÁRIO DO RYAN', 'conta_bancaria'::public.fin_forma_pagamento, 1275.00::numeric, 'Conta bancária', 'Janeiro', '2bd216776ac31975eac20451c8930a765b801a47'),
    (20, '2026-02-05'::date, '2026-02-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 12000.00::numeric, 'Conta bancária', '', '7cd392d69cbeb5ff2ade740926d99a371b59f0ac'),
    (21, '2026-02-06'::date, '2026-02-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'HOTMART', 'conta_bancaria'::public.fin_forma_pagamento, 2113.31::numeric, 'Conta bancária', '', 'b49b7a4311fc07d799f894bedfc2c00ac8e45ac2'),
    (22, '2026-02-07'::date, '2026-02-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', 'CERTIFICADO MEC', 'conta_bancaria'::public.fin_forma_pagamento, 2000.00::numeric, 'Conta bancária', 'Fevereiro', '373707b87c7d86f790a7594723eceeb88ee1f2de'),
    (23, '2026-02-09'::date, '2026-02-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'CANVA', 'cartao_credito'::public.fin_forma_pagamento, 24.15::numeric, 'Cartão de crédito', '', '4497b954f01f1ed72732bc34af0d66fecdd59c3d'),
    (24, '2026-02-10'::date, '2026-02-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contabilidade', 'CONTABILIZEI', 'cartao_credito'::public.fin_forma_pagamento, 189.15::numeric, 'Cartão de crédito', '', '932f81fc814b769fd1bbc1a94800c3cdb8170904'),
    (25, '2026-02-11'::date, '2026-01-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'INSS', 'DARF', 'conta_bancaria'::public.fin_forma_pagamento, 178.31::numeric, 'Conta bancária', 'Janeiro', 'df874f1b72f3c5c2a6133ec23cd17574a4e5339d'),
    (26, '2026-02-13'::date, '2026-01-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Imposto', 'IMPOSTO ATRASADO', 'conta_bancaria'::public.fin_forma_pagamento, 1320.56::numeric, 'Conta bancária', 'Janeiro', '774c3e11fa17d2d5f4449a4f058ab25386183e3c');

do $$
declare
  v_missing integer;
begin
  with tenant_scope as (
    select id as tenant_id
    from public.tenants
    where lower(nome) like '%juliana coutinho%'
    order by created_at
    limit 1
  ),
  checked as (
    select r.source_row
    from fin_import_raw r
    cross join tenant_scope t
    left join public.fin_centros_resultado cr
      on cr.tenant_id = t.tenant_id and cr.nome = r.centro
    left join public.fin_categorias c
      on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
    left join public.fin_subcategorias s
      on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
    left join public.fin_bancos b
      on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
    left join public.fin_cartoes ca
      on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
    left join public.fin_cursos cu
      on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
    where cr.id is null
       or c.id is null
       or s.id is null
       or (r.forma_pagamento <> 'cartao_credito' and b.id is null)
       or (r.forma_pagamento = 'cartao_credito' and ca.id is null)
       or (r.centro = 'Infoproduto' and r.tipo = 'entrada' and cu.id is null)
  )
  select count(*) into v_missing from checked;

  if v_missing > 0 then
    raise exception 'Financeiro importacao: % linhas sem cadastro de referencia', v_missing;
  end if;
end;
$$;

with tenant_scope as (
  select id as tenant_id
  from public.tenants
  where lower(nome) like '%juliana coutinho%'
  order by created_at
  limit 1
),
refs as (
  select
    r.*,
    t.tenant_id,
    cr.id as centro_resultado_id,
    c.id as categoria_id,
    s.id as subcategoria_id,
    b.id as banco_id,
    ca.id as cartao_id,
    cu.id as curso_id
  from fin_import_raw r
  cross join tenant_scope t
  join public.fin_centros_resultado cr
    on cr.tenant_id = t.tenant_id and cr.nome = r.centro
  join public.fin_categorias c
    on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
  join public.fin_subcategorias s
    on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
  left join public.fin_bancos b
    on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
  left join public.fin_cartoes ca
    on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
  left join public.fin_cursos cu
    on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
)
insert into public.fin_lancamentos (
  tenant_id, data_pagamento, mes_competencia, tipo, status,
  centro_resultado_id, categoria_id, subcategoria_id, curso_id,
  forma_pagamento, banco_id, cartao_id, qtd_parcelas, parcela_numero,
  descricao, valor, observacao, origem, status_origem, metadata
)
select
  tenant_id,
  data_pagamento,
  mes_competencia,
  tipo,
  'realizado'::public.fin_status_lancamento,
  centro_resultado_id,
  categoria_id,
  subcategoria_id,
  case when centro = 'Infoproduto' and tipo = 'entrada' then curso_id else null::uuid end,
  forma_pagamento,
  case when forma_pagamento = 'cartao_credito' then null::uuid else banco_id end,
  case when forma_pagamento = 'cartao_credito' then cartao_id else null::uuid end,
  1,
  1,
  descricao,
  valor,
  'Importado da planilha Fluxo de caixa V2',
  'importacao'::public.fin_origem_lancamento,
  'planilha_v2',
  jsonb_build_object(
    'source', 'TESTE Fluxo de caixa V2.xlsx',
    'source_row', source_row,
    'import_hash', import_hash,
    'raw_pagamento', raw_pagamento,
    'raw_mes_competencia', raw_mes_competencia
  )
from refs
where not exists (
  select 1
  from public.fin_lancamentos l
  where l.tenant_id = refs.tenant_id
    and l.origem = 'importacao'
    and l.metadata->>'import_hash' = refs.import_hash
);

commit;
