-- Auto-generated by scripts/generate_financeiro_seed.py
-- Source rows: 27..51

begin;

create temporary table if not exists fin_import_raw (
  source_row integer,
  data_pagamento date,
  mes_competencia date,
  centro text,
  tipo public.fin_tipo_lancamento,
  natureza text,
  categoria text,
  subcategoria text,
  descricao text,
  forma_pagamento public.fin_forma_pagamento,
  valor numeric(14,2),
  raw_pagamento text,
  raw_mes_competencia text,
  import_hash text
) on commit drop;

truncate table fin_import_raw;

insert into fin_import_raw (
  source_row, data_pagamento, mes_competencia, centro, tipo, natureza,
  categoria, subcategoria, descricao, forma_pagamento, valor,
  raw_pagamento, raw_mes_competencia, import_hash
)
values
    (27, '2026-02-19'::date, '2026-02-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'CONSELHO DE FONO', 'cartao_credito'::public.fin_forma_pagamento, 165.00::numeric, 'Cartão de crédito', '', '510c8024bd26fef692620e491f00608c412cd9f2'),
    (28, '2026-02-19'::date, '2026-02-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'MAQUINA DE LASER', 'conta_bancaria'::public.fin_forma_pagamento, 5762.28::numeric, 'Conta bancária', '', '5151312b8765e10fcab2d9f4672bec850f6efa69'),
    (29, '2026-02-19'::date, '2026-02-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'INTERNET', 'conta_bancaria'::public.fin_forma_pagamento, 104.69::numeric, 'Conta bancária', '', '3b37a97ae68511c21f1debf6b5f164e6991d4ed6'),
    (30, '2026-02-20'::date, '2026-02-01'::date, 'Não operacional', 'saida'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'TROCA DE DINHEIRO', 'conta_bancaria'::public.fin_forma_pagamento, 160.00::numeric, 'Conta bancária', '', 'be58fe49a83350000bcaa1c8e769cca6e18e7ee5'),
    (31, '2026-02-20'::date, '2026-02-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 180.00::numeric, 'Conta bancária', '', 'cb36cd7731d01d4a8eed06b5c142fee1836052a4'),
    (32, '2026-02-23'::date, '2026-02-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'EBOOK DE AASI', 'conta_bancaria'::public.fin_forma_pagamento, 97.00::numeric, 'Conta bancária', '', '7520f235daa50ad65961043c53b79331e6f1177c'),
    (33, '2026-03-02'::date, '2026-03-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 180.00::numeric, 'Conta bancária', '', 'affb455abebc993d46111764851881cf4efb2616'),
    (34, '2026-03-02'::date, '2026-03-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 200.00::numeric, 'Conta bancária', '', '4a0e8eed6cb8148fd80f76d1afb7c8b49686ffe5'),
    (35, '2026-03-03'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 5454.56::numeric, 'Conta bancária', '', '78173b8be8ed54843e814ec6859bc061241e9cde'),
    (36, '2026-03-04'::date, '2026-02-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Prestação de serviços', 'SALÁRIO DO RYAN', 'conta_bancaria'::public.fin_forma_pagamento, 1275.00::numeric, 'Conta bancária', 'Fevereiro', '88bdbdcfb07785617cafd8d6aad266553ef92c7d'),
    (37, '2026-03-05'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 195.00::numeric, 'Conta bancária', '', '8b196818551db344c0bf6ce8b749c9f015bc685d'),
    (38, '2026-03-06'::date, '2026-03-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', 'CERTIFICADO MEC', 'conta_bancaria'::public.fin_forma_pagamento, 2000.00::numeric, 'Conta bancária', 'Março', '2cc51500d84b307a29dca8765cf72622591ec3a6'),
    (39, '2026-03-06'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 885.01::numeric, 'Conta bancária', '', '56513ae545177d5e787c927289d3271170225363'),
    (40, '2026-03-06'::date, '2026-03-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 600.00::numeric, 'Conta bancária', '', '0ec126f9276d8b7b1ff5872e4eeb687bdb1b8e58'),
    (41, '2026-03-09'::date, '2026-03-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 951.00::numeric, 'Conta bancária', '', '49432c327c60d31f129f4e6803b6a5465d7a09d6'),
    (42, '2026-03-10'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contabilidade', 'CONTABILIZEI', 'cartao_credito'::public.fin_forma_pagamento, 195.00::numeric, 'Cartão de crédito', '', '7453a05638ecb4aca03fed232f4dd812ba8afe96'),
    (43, '2026-03-10'::date, '2026-03-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'CANVA', 'cartao_credito'::public.fin_forma_pagamento, 24.15::numeric, 'Cartão de crédito', '', '617bd95c8fa457fabe41e9af287a3829627996c1'),
    (44, '2026-03-10'::date, '2026-03-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'REPASSE NAYARA JANUARIO', 'conta_bancaria'::public.fin_forma_pagamento, 684.50::numeric, 'Conta bancária', '', '283190563a4a176a65f5f9eb1cf9df6da9669422'),
    (45, '2026-03-10'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 2270.57::numeric, 'Conta bancária', '', 'cb8801a5c922929c4b9efe9dcc7ad2be8d132274'),
    (46, '2026-03-11'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 4000.00::numeric, 'Conta bancária', '', 'c6f330de367b638c2188cd0e69c936da00a4be37'),
    (47, '2026-03-12'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'PREFEITURA PATRICIA', 'conta_bancaria'::public.fin_forma_pagamento, 1197.00::numeric, 'Conta bancária', '', '858020e48f0bbbf8c51782ff510799afe9bcbf5b'),
    (48, '2026-03-13'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'INTERNET', 'conta_bancaria'::public.fin_forma_pagamento, 102.00::numeric, 'Conta bancária', '', 'e218d1a15264bce63642d58a52c0cd8abc9e2126'),
    (49, '2026-03-13'::date, '2026-03-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 200.00::numeric, 'Conta bancária', '', '2f72f0d1404874e9c13524b7b2bc53c7b595fa41'),
    (50, '2026-03-18'::date, '2026-02-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'INSS', 'DARF', 'conta_bancaria'::public.fin_forma_pagamento, 178.31::numeric, 'Conta bancária', 'Fevereiro', '3042450a784e98569f89076866a6647dd39ec92a'),
    (51, '2026-03-19'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 2795.02::numeric, 'Conta bancária', '', '19496bb7043b24deacda4f2f7ba30e8904df1857');

do $$
declare
  v_missing integer;
begin
  with tenant_scope as (
    select id as tenant_id
    from public.tenants
    where lower(nome) like '%juliana coutinho%'
    order by created_at
    limit 1
  ),
  checked as (
    select r.source_row
    from fin_import_raw r
    cross join tenant_scope t
    left join public.fin_centros_resultado cr
      on cr.tenant_id = t.tenant_id and cr.nome = r.centro
    left join public.fin_categorias c
      on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
    left join public.fin_subcategorias s
      on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
    left join public.fin_bancos b
      on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
    left join public.fin_cartoes ca
      on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
    left join public.fin_cursos cu
      on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
    where cr.id is null
       or c.id is null
       or s.id is null
       or (r.forma_pagamento <> 'cartao_credito' and b.id is null)
       or (r.forma_pagamento = 'cartao_credito' and ca.id is null)
       or (r.centro = 'Infoproduto' and r.tipo = 'entrada' and cu.id is null)
  )
  select count(*) into v_missing from checked;

  if v_missing > 0 then
    raise exception 'Financeiro importacao: % linhas sem cadastro de referencia', v_missing;
  end if;
end;
$$;

with tenant_scope as (
  select id as tenant_id
  from public.tenants
  where lower(nome) like '%juliana coutinho%'
  order by created_at
  limit 1
),
refs as (
  select
    r.*,
    t.tenant_id,
    cr.id as centro_resultado_id,
    c.id as categoria_id,
    s.id as subcategoria_id,
    b.id as banco_id,
    ca.id as cartao_id,
    cu.id as curso_id
  from fin_import_raw r
  cross join tenant_scope t
  join public.fin_centros_resultado cr
    on cr.tenant_id = t.tenant_id and cr.nome = r.centro
  join public.fin_categorias c
    on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
  join public.fin_subcategorias s
    on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
  left join public.fin_bancos b
    on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
  left join public.fin_cartoes ca
    on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
  left join public.fin_cursos cu
    on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
)
insert into public.fin_lancamentos (
  tenant_id, data_pagamento, mes_competencia, tipo, status,
  centro_resultado_id, categoria_id, subcategoria_id, curso_id,
  forma_pagamento, banco_id, cartao_id, qtd_parcelas, parcela_numero,
  descricao, valor, observacao, origem, status_origem, metadata
)
select
  tenant_id,
  data_pagamento,
  mes_competencia,
  tipo,
  'realizado'::public.fin_status_lancamento,
  centro_resultado_id,
  categoria_id,
  subcategoria_id,
  case when centro = 'Infoproduto' and tipo = 'entrada' then curso_id else null::uuid end,
  forma_pagamento,
  case when forma_pagamento = 'cartao_credito' then null::uuid else banco_id end,
  case when forma_pagamento = 'cartao_credito' then cartao_id else null::uuid end,
  1,
  1,
  descricao,
  valor,
  'Importado da planilha Fluxo de caixa V2',
  'importacao'::public.fin_origem_lancamento,
  'planilha_v2',
  jsonb_build_object(
    'source', 'TESTE Fluxo de caixa V2.xlsx',
    'source_row', source_row,
    'import_hash', import_hash,
    'raw_pagamento', raw_pagamento,
    'raw_mes_competencia', raw_mes_competencia
  )
from refs
where not exists (
  select 1
  from public.fin_lancamentos l
  where l.tenant_id = refs.tenant_id
    and l.origem = 'importacao'
    and l.metadata->>'import_hash' = refs.import_hash
);

commit;
