-- Auto-generated by scripts/generate_financeiro_seed.py
-- Source rows: 52..76

begin;

create temporary table if not exists fin_import_raw (
  source_row integer,
  data_pagamento date,
  mes_competencia date,
  centro text,
  tipo public.fin_tipo_lancamento,
  natureza text,
  categoria text,
  subcategoria text,
  descricao text,
  forma_pagamento public.fin_forma_pagamento,
  valor numeric(14,2),
  raw_pagamento text,
  raw_mes_competencia text,
  import_hash text
) on commit drop;

truncate table fin_import_raw;

insert into fin_import_raw (
  source_row, data_pagamento, mes_competencia, centro, tipo, natureza,
  categoria, subcategoria, descricao, forma_pagamento, valor,
  raw_pagamento, raw_mes_competencia, import_hash
)
values
    (52, '2026-03-19'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 2304.68::numeric, 'Conta bancária', '', 'a976995adb9508705aef20dc66f034b22cc2cf72'),
    (53, '2026-03-20'::date, '2026-03-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Equipamentos e materiais', 'SESSÃO DE FOTOS', 'conta_bancaria'::public.fin_forma_pagamento, 495.00::numeric, 'Conta bancária', '', 'df3d84384d40dd8c77f21a2a04c83043e75591ed'),
    (54, '2026-03-20'::date, '2026-02-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Imposto', 'DASS', 'conta_bancaria'::public.fin_forma_pagamento, 4388.78::numeric, 'Conta bancária', 'Fevereiro', '7024a38d7291df20b7811dbe81933e880026f01a'),
    (55, '2026-03-25'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 1500.00::numeric, 'Conta bancária', '', '8e97a17c456ea7d2fb2fc726a3cee579a501b919'),
    (56, '2026-03-25'::date, '2026-03-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 1314.43::numeric, 'Conta bancária', '', '4efbb1d81377ad01f677eb1843e025f5298b4988'),
    (57, '2026-03-27'::date, '2026-03-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'ATENDIMENTO', 'conta_bancaria'::public.fin_forma_pagamento, 400.00::numeric, 'Conta bancária', '', '3ec7cffd588a2a5ea88e3b7d8804ce90d9b281f0'),
    (58, '2026-03-30'::date, '2026-03-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'REPASSE NAYARA JANUARIO', 'conta_bancaria'::public.fin_forma_pagamento, 200.00::numeric, 'Conta bancária', '', '38c5f6a035caf0396e9decc0dea775a12bff8ae8'),
    (59, '2026-04-01'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 1500.00::numeric, 'Conta bancária', '', 'd60ff824e5097c14d0e1e9b05a1f7c35affcd419'),
    (60, '2026-04-02'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 766.86::numeric, 'Conta bancária', '', '212eb77be93c41fbba707ab751a1ef45f51a05ba'),
    (61, '2026-04-02'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 4972.51::numeric, 'Conta bancária', '', 'a6a9e7e7a2a97f56f6923102c540a89d74b8db56'),
    (62, '2026-04-02'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'HOTMART', 'conta_bancaria'::public.fin_forma_pagamento, 993.69::numeric, 'Conta bancária', '', 'eb4c15edb5680dc10936e35bca8a29fbaf452924'),
    (63, '2026-04-02'::date, '2026-03-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Prestação de serviços', 'SALÁRIO DO RYAN', 'conta_bancaria'::public.fin_forma_pagamento, 1275.00::numeric, 'Conta bancária', 'Março', 'd0a3a1cd1f98f159711c27da9907d01bd955421d'),
    (64, '2026-04-02'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Pessoal', 'Prestação de serviços', 'BENEFÍCIOS PARA FUNCIONÁRIO', 'conta_bancaria'::public.fin_forma_pagamento, 16.00::numeric, 'Conta bancária', 'Março', '92210dd5cd595d58da9420ce9f5fac99aa278a96'),
    (65, '2026-04-02'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 6060.00::numeric, 'Conta bancária', '', 'fb780ce085bd4c7503b37bc226afe530fb7f0017'),
    (66, '2026-04-10'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 3.46::numeric, 'Conta bancária', '', '36c7fd5ba2d21a59b8f74186be907b0a669bbb04'),
    (67, '2026-04-13'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 525.14::numeric, 'Conta bancária', '', 'a312ad323849658c3a78d1459bce0f1e0a1552a8'),
    (68, '2026-04-13'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 5678.07::numeric, 'Conta bancária', '', 'fb07ed6ef7ea3ccc78761fb9ea2b2bf125005ab3'),
    (69, '2026-04-13'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 4000.00::numeric, 'Conta bancária', '', '594a4654e4080dcaa28c1ba11f89ecc49a3e4942'),
    (70, '2026-04-13'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contabilidade', 'CONTABILIZEI', 'cartao_credito'::public.fin_forma_pagamento, 214.90::numeric, 'Cartão de crédito', '', '5a5c1331dcd4b82a5d9478ec9848c1e3bd553a9a'),
    (71, '2026-04-13'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'CANVA', 'cartao_credito'::public.fin_forma_pagamento, 24.15::numeric, 'Cartão de crédito', '', '4da99ac6073bfc3238be497d87ba68ff1a747614'),
    (72, '2026-04-13'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'HOTMART', 'conta_bancaria'::public.fin_forma_pagamento, 653.69::numeric, 'Conta bancária', '', 'c2fe50cb9f71214f39d21740aa953e62f3f0937b'),
    (73, '2026-04-13'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Administrativas', 'Contas fixas', 'INTERNET', 'conta_bancaria'::public.fin_forma_pagamento, 99.99::numeric, 'Conta bancária', '', 'c6798b5f6a63a3a7dabf4c16c86febd5cd02f605'),
    (74, '2026-04-14'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'HOSTGATOR', 'conta_bancaria'::public.fin_forma_pagamento, 221.88::numeric, 'Conta bancária', '', 'e1486bb022c1c87319905337469e30a882258bef'),
    (75, '2026-04-14'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'HOSTGATOR', 'conta_bancaria'::public.fin_forma_pagamento, 151.08::numeric, 'Conta bancária', '', '65aa30b16b5406eef9a045330fb0fd9991894e63'),
    (76, '2026-04-14'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'HOSTGATOR', 'conta_bancaria'::public.fin_forma_pagamento, 67.99::numeric, 'Conta bancária', '', 'ea34358f5d49433876cc006aac6462f7a945927f');

do $$
declare
  v_missing integer;
begin
  with tenant_scope as (
    select id as tenant_id
    from public.tenants
    where lower(nome) like '%juliana coutinho%'
    order by created_at
    limit 1
  ),
  checked as (
    select r.source_row
    from fin_import_raw r
    cross join tenant_scope t
    left join public.fin_centros_resultado cr
      on cr.tenant_id = t.tenant_id and cr.nome = r.centro
    left join public.fin_categorias c
      on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
    left join public.fin_subcategorias s
      on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
    left join public.fin_bancos b
      on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
    left join public.fin_cartoes ca
      on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
    left join public.fin_cursos cu
      on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
    where cr.id is null
       or c.id is null
       or s.id is null
       or (r.forma_pagamento <> 'cartao_credito' and b.id is null)
       or (r.forma_pagamento = 'cartao_credito' and ca.id is null)
       or (r.centro = 'Infoproduto' and r.tipo = 'entrada' and cu.id is null)
  )
  select count(*) into v_missing from checked;

  if v_missing > 0 then
    raise exception 'Financeiro importacao: % linhas sem cadastro de referencia', v_missing;
  end if;
end;
$$;

with tenant_scope as (
  select id as tenant_id
  from public.tenants
  where lower(nome) like '%juliana coutinho%'
  order by created_at
  limit 1
),
refs as (
  select
    r.*,
    t.tenant_id,
    cr.id as centro_resultado_id,
    c.id as categoria_id,
    s.id as subcategoria_id,
    b.id as banco_id,
    ca.id as cartao_id,
    cu.id as curso_id
  from fin_import_raw r
  cross join tenant_scope t
  join public.fin_centros_resultado cr
    on cr.tenant_id = t.tenant_id and cr.nome = r.centro
  join public.fin_categorias c
    on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
  join public.fin_subcategorias s
    on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
  left join public.fin_bancos b
    on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
  left join public.fin_cartoes ca
    on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
  left join public.fin_cursos cu
    on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
)
insert into public.fin_lancamentos (
  tenant_id, data_pagamento, mes_competencia, tipo, status,
  centro_resultado_id, categoria_id, subcategoria_id, curso_id,
  forma_pagamento, banco_id, cartao_id, qtd_parcelas, parcela_numero,
  descricao, valor, observacao, origem, status_origem, metadata
)
select
  tenant_id,
  data_pagamento,
  mes_competencia,
  tipo,
  'realizado'::public.fin_status_lancamento,
  centro_resultado_id,
  categoria_id,
  subcategoria_id,
  case when centro = 'Infoproduto' and tipo = 'entrada' then curso_id else null::uuid end,
  forma_pagamento,
  case when forma_pagamento = 'cartao_credito' then null::uuid else banco_id end,
  case when forma_pagamento = 'cartao_credito' then cartao_id else null::uuid end,
  1,
  1,
  descricao,
  valor,
  'Importado da planilha Fluxo de caixa V2',
  'importacao'::public.fin_origem_lancamento,
  'planilha_v2',
  jsonb_build_object(
    'source', 'TESTE Fluxo de caixa V2.xlsx',
    'source_row', source_row,
    'import_hash', import_hash,
    'raw_pagamento', raw_pagamento,
    'raw_mes_competencia', raw_mes_competencia
  )
from refs
where not exists (
  select 1
  from public.fin_lancamentos l
  where l.tenant_id = refs.tenant_id
    and l.origem = 'importacao'
    and l.metadata->>'import_hash' = refs.import_hash
);

commit;
