-- Auto-generated by scripts/generate_financeiro_seed.py
-- Source rows: 77..101

begin;

create temporary table if not exists fin_import_raw (
  source_row integer,
  data_pagamento date,
  mes_competencia date,
  centro text,
  tipo public.fin_tipo_lancamento,
  natureza text,
  categoria text,
  subcategoria text,
  descricao text,
  forma_pagamento public.fin_forma_pagamento,
  valor numeric(14,2),
  raw_pagamento text,
  raw_mes_competencia text,
  import_hash text
) on commit drop;

truncate table fin_import_raw;

insert into fin_import_raw (
  source_row, data_pagamento, mes_competencia, centro, tipo, natureza,
  categoria, subcategoria, descricao, forma_pagamento, valor,
  raw_pagamento, raw_mes_competencia, import_hash
)
values
    (77, '2026-04-15'::date, '2026-04-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'ALIMENTAÇÃO EVENTO CLÍNICA', 'conta_bancaria'::public.fin_forma_pagamento, 600.00::numeric, 'Conta bancária', '', 'f8917885a64b11052a62affb1d3ca0579cd9669f'),
    (78, '2026-04-19'::date, '2026-04-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'ALIMENTAÇÃO EVENTO CLÍNICA', 'conta_bancaria'::public.fin_forma_pagamento, 650.00::numeric, 'Conta bancária', '', '5c95903037af21742470afc2580315e57a374b70'),
    (79, '2026-04-20'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 4754.63::numeric, 'Conta bancária', '', 'e4b0c4aef9022d95970c351610e8da0b3bb889da'),
    (80, '2026-04-20'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 160.72::numeric, 'Conta bancária', '', 'd2baaa2807143494673d7b4c14b7a08426369fa5'),
    (81, '2026-04-20'::date, '2026-03-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'INSS', 'DARF', 'conta_bancaria'::public.fin_forma_pagamento, 178.31::numeric, 'Conta bancária', 'Março', '1f29003f73dc1f0e22318bc378a075443abcc488'),
    (82, '2026-04-20'::date, '2026-03-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Imposto', 'DASS', 'conta_bancaria'::public.fin_forma_pagamento, 5586.13::numeric, 'Conta bancária', 'Março', '865c1fa88043fcf45f55a2473c223097b0808109'),
    (83, '2026-04-20'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Administrativas', 'Equipamentos e materiais', 'SESSÃO DE FOTOS', 'conta_bancaria'::public.fin_forma_pagamento, 495.00::numeric, 'Conta bancária', '', 'b36307bd8c513fb173192213a059f8d9f18af48d'),
    (84, '2026-04-22'::date, '2026-04-01'::date, 'Não operacional', 'entrada'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'SAQUE CDB', 'conta_bancaria'::public.fin_forma_pagamento, 300.00::numeric, 'Conta bancária', '', '31fb9fc9ddb489e13d01b26a660288f5074f7964'),
    (85, '2026-04-22'::date, '2026-04-01'::date, 'Não operacional', 'entrada'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'SAQUE CDB', 'conta_bancaria'::public.fin_forma_pagamento, 600.00::numeric, 'Conta bancária', '', '5fcd205769c137d81522a68865f47fa8f6536b21'),
    (86, '2026-04-22'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 200.00::numeric, 'Conta bancária', '', 'c47ddc3274431d03e066c34a199b37e437d34806'),
    (87, '2026-04-23'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 484.38::numeric, 'Conta bancária', '', '8f0c3e4f0e46850d8112eac17ffbfca053e3904f'),
    (88, '2026-04-23'::date, '2026-04-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'TAXA EQUIPAMENTO CLÍNICA', 'conta_bancaria'::public.fin_forma_pagamento, 591.00::numeric, 'Conta bancária', '', '4b50112f0e7b67847bc29e5f585c98d1cba8cace'),
    (89, '2026-04-23'::date, '2026-04-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 382.03::numeric, 'Conta bancária', '', '86118691a2363e4c181ee1c510a3f8728b16d272'),
    (90, '2026-04-13'::date, '2026-04-01'::date, 'Não operacional', 'entrada'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'SAQUE CDB', 'conta_bancaria'::public.fin_forma_pagamento, 239.06::numeric, 'Conta bancária', '', 'eed0f81862b3f94b77257b385128b3be4c8a170f'),
    (91, '2026-04-28'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Distribuição dos Lucros', 'DISTRIBUIÇÃO DOS LUCROS', 'conta_bancaria'::public.fin_forma_pagamento, 500.00::numeric, 'Conta bancária', '', '7a7d83274009b0fa454b379d84fa703d559ae94d'),
    (92, '2026-05-04'::date, '2026-05-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 19203.07::numeric, 'Conta bancária', '', '226aef5e4fce60711d8b09ef5c42b28503f33743'),
    (93, '2026-05-04'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Prestação de serviços', 'SALÁRIO DO RYAN', 'conta_bancaria'::public.fin_forma_pagamento, 1275.00::numeric, 'Conta bancária', 'Abril', 'fd69137e6ffaa4107ed91fb31ba393ba500fe91a'),
    (94, '2026-05-05'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', 'PROFESSORA CONVIDADA', 'conta_bancaria'::public.fin_forma_pagamento, 906.00::numeric, 'Conta bancária', 'Abril', 'f2d9bb5c6aaa9d427de320067002ac9740bd38b6'),
    (95, '2026-05-05'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', 'PROFESSORA CONVIDADA', 'conta_bancaria'::public.fin_forma_pagamento, 744.00::numeric, 'Conta bancária', 'Abril', '9910c3a547b81d7ccdc2e06e9cae306c412e1915'),
    (96, '2026-05-05'::date, '2026-05-01'::date, 'Clínica', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Clínica', 'Clínica', 'REPASSE AURALABS', 'conta_bancaria'::public.fin_forma_pagamento, 2428.38::numeric, 'Conta bancária', '', '79e208196aa8038182ea49fde4dd63a240e95e8d'),
    (97, '2026-05-05'::date, '2026-05-01'::date, 'Não operacional', 'entrada'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'CDB BANCO INTER', 'conta_bancaria'::public.fin_forma_pagamento, 1586.24::numeric, 'Conta bancária', '', '5dabf09d5903ea95b08bc60f7a915db8a8eb4f4a'),
    (98, '2026-05-05'::date, '2026-05-01'::date, 'Clínica', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Clínica', 'VENDA APARELHO', 'conta_bancaria'::public.fin_forma_pagamento, 1452.00::numeric, 'Conta bancária', '', 'f9cc67b73bfaf9957568e4ba8b5785f41551eaf2'),
    (99, '2026-05-05'::date, '2026-05-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 7000.00::numeric, 'Conta bancária', '', '9aa82b27c0b903e53cef2b440859a28fab0e5dec'),
    (100, '2026-05-05'::date, '2026-05-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 1000.00::numeric, 'Conta bancária', '', '640dd2ad4f6fde1146c017b9834785a717f8bee3'),
    (101, '2026-05-07'::date, '2026-05-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Pessoal', 'Contabilidade', 'CONTABILIZEI', 'cartao_credito'::public.fin_forma_pagamento, 344.00::numeric, 'Cartão de crédito', '', 'a9247102fb69963ebb7f1c52782549ba8ec59f32');

do $$
declare
  v_missing integer;
begin
  with tenant_scope as (
    select id as tenant_id
    from public.tenants
    where lower(nome) like '%juliana coutinho%'
    order by created_at
    limit 1
  ),
  checked as (
    select r.source_row
    from fin_import_raw r
    cross join tenant_scope t
    left join public.fin_centros_resultado cr
      on cr.tenant_id = t.tenant_id and cr.nome = r.centro
    left join public.fin_categorias c
      on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
    left join public.fin_subcategorias s
      on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
    left join public.fin_bancos b
      on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
    left join public.fin_cartoes ca
      on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
    left join public.fin_cursos cu
      on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
    where cr.id is null
       or c.id is null
       or s.id is null
       or (r.forma_pagamento <> 'cartao_credito' and b.id is null)
       or (r.forma_pagamento = 'cartao_credito' and ca.id is null)
       or (r.centro = 'Infoproduto' and r.tipo = 'entrada' and cu.id is null)
  )
  select count(*) into v_missing from checked;

  if v_missing > 0 then
    raise exception 'Financeiro importacao: % linhas sem cadastro de referencia', v_missing;
  end if;
end;
$$;

with tenant_scope as (
  select id as tenant_id
  from public.tenants
  where lower(nome) like '%juliana coutinho%'
  order by created_at
  limit 1
),
refs as (
  select
    r.*,
    t.tenant_id,
    cr.id as centro_resultado_id,
    c.id as categoria_id,
    s.id as subcategoria_id,
    b.id as banco_id,
    ca.id as cartao_id,
    cu.id as curso_id
  from fin_import_raw r
  cross join tenant_scope t
  join public.fin_centros_resultado cr
    on cr.tenant_id = t.tenant_id and cr.nome = r.centro
  join public.fin_categorias c
    on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
  join public.fin_subcategorias s
    on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
  left join public.fin_bancos b
    on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
  left join public.fin_cartoes ca
    on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
  left join public.fin_cursos cu
    on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
)
insert into public.fin_lancamentos (
  tenant_id, data_pagamento, mes_competencia, tipo, status,
  centro_resultado_id, categoria_id, subcategoria_id, curso_id,
  forma_pagamento, banco_id, cartao_id, qtd_parcelas, parcela_numero,
  descricao, valor, observacao, origem, status_origem, metadata
)
select
  tenant_id,
  data_pagamento,
  mes_competencia,
  tipo,
  'realizado'::public.fin_status_lancamento,
  centro_resultado_id,
  categoria_id,
  subcategoria_id,
  case when centro = 'Infoproduto' and tipo = 'entrada' then curso_id else null::uuid end,
  forma_pagamento,
  case when forma_pagamento = 'cartao_credito' then null::uuid else banco_id end,
  case when forma_pagamento = 'cartao_credito' then cartao_id else null::uuid end,
  1,
  1,
  descricao,
  valor,
  'Importado da planilha Fluxo de caixa V2',
  'importacao'::public.fin_origem_lancamento,
  'planilha_v2',
  jsonb_build_object(
    'source', 'TESTE Fluxo de caixa V2.xlsx',
    'source_row', source_row,
    'import_hash', import_hash,
    'raw_pagamento', raw_pagamento,
    'raw_mes_competencia', raw_mes_competencia
  )
from refs
where not exists (
  select 1
  from public.fin_lancamentos l
  where l.tenant_id = refs.tenant_id
    and l.origem = 'importacao'
    and l.metadata->>'import_hash' = refs.import_hash
);

commit;
