-- Auto-generated by scripts/generate_financeiro_seed.py
-- Source rows: 102..111

begin;

create temporary table if not exists fin_import_raw (
  source_row integer,
  data_pagamento date,
  mes_competencia date,
  centro text,
  tipo public.fin_tipo_lancamento,
  natureza text,
  categoria text,
  subcategoria text,
  descricao text,
  forma_pagamento public.fin_forma_pagamento,
  valor numeric(14,2),
  raw_pagamento text,
  raw_mes_competencia text,
  import_hash text
) on commit drop;

truncate table fin_import_raw;

insert into fin_import_raw (
  source_row, data_pagamento, mes_competencia, centro, tipo, natureza,
  categoria, subcategoria, descricao, forma_pagamento, valor,
  raw_pagamento, raw_mes_competencia, import_hash
)
values
    (102, '2026-05-07'::date, '2026-05-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Operacionais', 'Softwares e ferramentas', 'CANVA', 'cartao_credito'::public.fin_forma_pagamento, 24.15::numeric, 'Cartão de crédito', '', '181b3cf4e01d24da85231e72dec4bc2709674249'),
    (103, '2026-05-07'::date, '2026-05-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', '360IMPRIMIR', 'cartao_credito'::public.fin_forma_pagamento, 782.74::numeric, 'Cartão de crédito', 'Maio', 'fbfb798916eb3898f82c8b664786ea2d884262e2'),
    (104, '2026-05-07'::date, '2026-05-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Pedagógico', 'ELO7', 'cartao_credito'::public.fin_forma_pagamento, 244.89::numeric, 'Cartão de crédito', 'Maio', '428cfd7a71ffa52efa949db3f6b79bc0137f1e79'),
    (105, '2026-05-07'::date, '2026-05-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Equipamentos e materiais', 'MICROFONE', 'conta_bancaria'::public.fin_forma_pagamento, 100.00::numeric, 'Conta bancária', '', '06940fbb796e0365b4e030c9880c9652bd8c6cb3'),
    (106, '2026-05-08'::date, '2026-05-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'GREENN', 'conta_bancaria'::public.fin_forma_pagamento, 6415.00::numeric, 'Conta bancária', '', '18fd2e396d128b391074d0b770df7e2b88ee82e3'),
    (107, '2026-05-11'::date, '2026-05-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'Pro-labore', 'PRÓ-LABORE', 'conta_bancaria'::public.fin_forma_pagamento, 4000.00::numeric, 'Conta bancária', '', 'f206dabd603d213b4add8d318ab3972140230e04'),
    (108, '2026-05-15'::date, '2026-05-01'::date, 'Infoproduto', 'entrada'::public.fin_tipo_lancamento, 'Operacional', 'Entradas', 'Entradas', 'TMB', 'conta_bancaria'::public.fin_forma_pagamento, 1487.61::numeric, 'Conta bancária', '', 'ab1a000dcfe72025f1faffbccecc0f1a726b6d76'),
    (109, '2026-05-20'::date, '2026-04-01'::date, 'Administrativo fixo', 'saida'::public.fin_tipo_lancamento, 'Fixo', 'Despesas Pessoal', 'INSS', 'DARF', 'conta_bancaria'::public.fin_forma_pagamento, 178.31::numeric, 'Conta bancária', 'Abril', 'bf4706e81e2e8974f3a8f9f2a4e3a9556272efaf'),
    (110, '2026-05-20'::date, '2026-04-01'::date, 'Infoproduto', 'saida'::public.fin_tipo_lancamento, 'Variável', 'Despesas Operacionais', 'Imposto', 'DASS', 'conta_bancaria'::public.fin_forma_pagamento, 3776.37::numeric, 'Conta bancária', 'Abril', '62cf26eccac352b1823ffb802f1bde59d7ae508a'),
    (111, '2026-05-20'::date, '2026-05-01'::date, 'Não operacional', 'saida'::public.fin_tipo_lancamento, 'Não operacional', 'Movimentações Financeiras', 'Movimentações Financeiras', 'CDB BANCO INTER', 'conta_bancaria'::public.fin_forma_pagamento, 2800.00::numeric, 'Conta bancária', '', '41c7bb88642787785578e1e2518064e64cad20a7');

do $$
declare
  v_missing integer;
begin
  with tenant_scope as (
    select id as tenant_id
    from public.tenants
    where lower(nome) like '%juliana coutinho%'
    order by created_at
    limit 1
  ),
  checked as (
    select r.source_row
    from fin_import_raw r
    cross join tenant_scope t
    left join public.fin_centros_resultado cr
      on cr.tenant_id = t.tenant_id and cr.nome = r.centro
    left join public.fin_categorias c
      on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
    left join public.fin_subcategorias s
      on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
    left join public.fin_bancos b
      on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
    left join public.fin_cartoes ca
      on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
    left join public.fin_cursos cu
      on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
    where cr.id is null
       or c.id is null
       or s.id is null
       or (r.forma_pagamento <> 'cartao_credito' and b.id is null)
       or (r.forma_pagamento = 'cartao_credito' and ca.id is null)
       or (r.centro = 'Infoproduto' and r.tipo = 'entrada' and cu.id is null)
  )
  select count(*) into v_missing from checked;

  if v_missing > 0 then
    raise exception 'Financeiro importacao: % linhas sem cadastro de referencia', v_missing;
  end if;
end;
$$;

with tenant_scope as (
  select id as tenant_id
  from public.tenants
  where lower(nome) like '%juliana coutinho%'
  order by created_at
  limit 1
),
refs as (
  select
    r.*,
    t.tenant_id,
    cr.id as centro_resultado_id,
    c.id as categoria_id,
    s.id as subcategoria_id,
    b.id as banco_id,
    ca.id as cartao_id,
    cu.id as curso_id
  from fin_import_raw r
  cross join tenant_scope t
  join public.fin_centros_resultado cr
    on cr.tenant_id = t.tenant_id and cr.nome = r.centro
  join public.fin_categorias c
    on c.tenant_id = t.tenant_id and c.tipo = r.tipo and c.nome = r.categoria
  join public.fin_subcategorias s
    on s.tenant_id = t.tenant_id and s.categoria_id = c.id and s.nome = r.subcategoria
  left join public.fin_bancos b
    on b.tenant_id = t.tenant_id and b.nome = 'Histórico (a reclassificar)'
  left join public.fin_cartoes ca
    on ca.tenant_id = t.tenant_id and ca.nome = 'Histórico (a reclassificar)'
  left join public.fin_cursos cu
    on cu.tenant_id = t.tenant_id and cu.nome = 'Histórico (a reclassificar)'
)
insert into public.fin_lancamentos (
  tenant_id, data_pagamento, mes_competencia, tipo, status,
  centro_resultado_id, categoria_id, subcategoria_id, curso_id,
  forma_pagamento, banco_id, cartao_id, qtd_parcelas, parcela_numero,
  descricao, valor, observacao, origem, status_origem, metadata
)
select
  tenant_id,
  data_pagamento,
  mes_competencia,
  tipo,
  'realizado'::public.fin_status_lancamento,
  centro_resultado_id,
  categoria_id,
  subcategoria_id,
  case when centro = 'Infoproduto' and tipo = 'entrada' then curso_id else null::uuid end,
  forma_pagamento,
  case when forma_pagamento = 'cartao_credito' then null::uuid else banco_id end,
  case when forma_pagamento = 'cartao_credito' then cartao_id else null::uuid end,
  1,
  1,
  descricao,
  valor,
  'Importado da planilha Fluxo de caixa V2',
  'importacao'::public.fin_origem_lancamento,
  'planilha_v2',
  jsonb_build_object(
    'source', 'TESTE Fluxo de caixa V2.xlsx',
    'source_row', source_row,
    'import_hash', import_hash,
    'raw_pagamento', raw_pagamento,
    'raw_mes_competencia', raw_mes_competencia
  )
from refs
where not exists (
  select 1
  from public.fin_lancamentos l
  where l.tenant_id = refs.tenant_id
    and l.origem = 'importacao'
    and l.metadata->>'import_hash' = refs.import_hash
);

commit;
