alter table public.landing_page_tracking_events
  add column if not exists visitor_id text,
  add column if not exists meta_campaign_id text,
  add column if not exists meta_adset_id text,
  add column if not exists meta_ad_id text,
  add column if not exists fbclid text;

create index if not exists landing_page_tracking_events_session_identity_idx
  on public.landing_page_tracking_events (tenant_id, session_id, occurred_at desc);

create index if not exists landing_page_tracking_events_meta_ad_idx
  on public.landing_page_tracking_events (tenant_id, meta_campaign_id, meta_adset_id, meta_ad_id, occurred_at desc)
  where meta_ad_id is not null;

comment on column public.landing_page_tracking_events.visitor_id is
  'Anonymous visitor identifier generated by the landing tracking runtime.';
comment on column public.landing_page_tracking_events.meta_campaign_id is
  'Meta campaign ID received from deterministic URL parameters.';
comment on column public.landing_page_tracking_events.meta_adset_id is
  'Meta ad set ID received from deterministic URL parameters.';
comment on column public.landing_page_tracking_events.meta_ad_id is
  'Meta ad ID received from deterministic URL parameters.';
comment on column public.landing_page_tracking_events.fbclid is
  'Meta click identifier received on the landing URL.';
